### ISSUE TITLE
Incompatibility with the new Chisel / CTM version

### ISSUE THREAD

**Issue by MatthiasMann** [OreCruncher/DynamicSurroundings#111]
Mod Version:
DynamicSurroundings-1.10.2-3.4.5.4.jar
Chisel-MC1.10.2-0.0.11.25.jar
CTM-MC1.10.2-0.1.0.13.jar

Forge Version:
12.18.3.2297

Error message while starting (no crash):
[07:56:17] [Client thread/WARN]: Unable to locate team.chisel.api.IFacade.getFacade()
[07:56:17] [Client thread/ERROR]: catching
java.lang.ClassNotFoundException: team.chisel.api.IFacade
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_121]
	at org.blockartistry.DynSurround.facade.ChiselFacadeAccessor.<clinit>(ChiselFacadeAccessor.java:50) [ChiselFacadeAccessor.class:?]
	at org.blockartistry.DynSurround.facade.FacadeHelper.<clinit>(FacadeHelper.java:49) [FacadeHelper.class:?]
	at org.blockartistry.DynSurround.client.footsteps.implem.BlockMap.getBlockAcoustics(BlockMap.java:135) [BlockMap.class:?]
	at org.blockartistry.DynSurround.client.footsteps.system.Solver.findAssociationForBlock(Solver.java:252) [Solver.class:?]
	at org.blockartistry.DynSurround.client.footsteps.system.Solver.findAssociationForLocation(Solver.java:151) [Solver.class:?]
	at org.blockartistry.DynSurround.client.footsteps.system.Solver.findAssociationForPlayer(Solver.java:125) [Solver.class:?]
	at org.blockartistry.DynSurround.client.footsteps.system.Generator.playSinglefoot(Generator.java:274) [Generator.class:?]
	at org.blockartistry.DynSurround.client.footsteps.system.Generator.simulateJumpingLanding(Generator.java:237) [Generator.class:?]
	at org.blockartistry.DynSurround.client.footsteps.system.Generator.simulateAirborne(Generator.java:199) [Generator.class:?]
	at org.blockartistry.DynSurround.client.footsteps.system.Generator.generateFootsteps(Generator.java:77) [Generator.class:?]
	at org.blockartistry.DynSurround.client.footsteps.system.Isolator.onFrame(Isolator.java:59) [Isolator.class:?]
	at org.blockartistry.DynSurround.registry.FootstepsRegistry.process(FootstepsRegistry.java:233) [FootstepsRegistry.class:?]
	at org.blockartistry.DynSurround.client.handlers.FootstepsHandler.process(FootstepsHandler.java:64) [FootstepsHandler.class:?]
	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:118) [EffectManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1035_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
[07:56:17] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: java.lang.ClassNotFoundException: team.chisel.api.IFacade
[07:56:17] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[07:56:17] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[07:56:17] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[07:56:17] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at java.lang.Class.forName0(Native Method)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at java.lang.Class.forName(Class.java:264)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.facade.ChiselFacadeAccessor.<clinit>(ChiselFacadeAccessor.java:50)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.facade.FacadeHelper.<clinit>(FacadeHelper.java:49)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.implem.BlockMap.getBlockAcoustics(BlockMap.java:135)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.system.Solver.findAssociationForBlock(Solver.java:252)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.system.Solver.findAssociationForLocation(Solver.java:151)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.system.Solver.findAssociationForPlayer(Solver.java:125)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.system.Generator.playSinglefoot(Generator.java:274)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.system.Generator.simulateJumpingLanding(Generator.java:237)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.system.Generator.simulateAirborne(Generator.java:199)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.system.Generator.generateFootsteps(Generator.java:77)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.footsteps.system.Isolator.onFrame(Isolator.java:59)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.registry.FootstepsRegistry.process(FootstepsRegistry.java:233)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.handlers.FootstepsHandler.process(FootstepsHandler.java:64)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:118)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1035_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[07:56:18] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:catching:114]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[07:56:18] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException

Description:
Chisel split the rendering part of into the CTM lib - the IFacade API was also moved.
The new class is team.chisel.ctm.api.IFacade with the modid "ctm-api".

**Comment by OreCruncher** [comment]
*cries*  I will check it out.

**Comment by MatthiasMann** [comment]
EnderIO supports both the old and new IFacade API:
https://github.com/SleepyTrousers/EnderIO/commit/708164dc509978839eae02e25d8af19f1d0915e1
https://github.com/SleepyTrousers/EnderIO/commit/4a0da269f89c84306d8a5f343995915480c4f167

In case you want to borrow the code feel free.

**Comment by OreCruncher** [comment]
Actually it is a pretty easy change assuming I can get the right API JAR.

**Comment by OreCruncher** [comment]
Getting this when debugging:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisel (chisel)
Caused by: java.lang.NoSuchMethodError: team.chisel.api.block.ChiselBlockBuilder$VariationBuilder.addOreDict(Ljava/lang/String;)Lteam/chisel/api/block/ChiselBlockBuilder$VariationBuilder;
```
Usually something stupid on my end.

**Comment by OreCruncher** [comment]
Pushed v3.4.5.5 version with support for the new Chisel API layout.
