### ISSUE TITLE
Crash with Auroras and Advanced Rocketry

### ISSUE THREAD

**Issue by alex2069** [OreCruncher/DynamicSurroundings#118]
*Forge Version:*
12.18.3.2297
Using FTB Beyond 1.8.1 + with extra mods

*Description:*
A crash occurs when simply opening a rocket's guidance module of all things.
After the first crash (on older version - second stack trace below), updated to latest at the time but still crashed. Then disabled Auroras on both server and client side, though still crashes. Have unfortunately had to remove Dynamic Surroundings. :(

On recent version:
UCHIJA	advancedRocketry{1.2.2} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.2.2.jar) 
UCHIJA	dsurround{3.4.5.3} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.4.5.3.jar) 

```
java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.WorldProvider.getSunBrightnessFactor(WorldProvider.java:399)
	at org.blockartistry.lib.DiurnalUtils.getCycle(DiurnalUtils.java:59)
	at org.blockartistry.lib.DiurnalUtils.isAuroraInvisible(DiurnalUtils.java:78)
	at org.blockartistry.lib.DiurnalUtils.isAuroraVisible(DiurnalUtils.java:74)
	at org.blockartistry.DynSurround.client.handlers.ExpressionStateHandler$5.update(ExpressionStateHandler.java:101)
	at org.blockartistry.DynSurround.client.handlers.ExpressionStateHandler.process(ExpressionStateHandler.java:499)
	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:118)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1908_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

On older version:
UCHIJA	advancedRocketry{1.0.19} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.0.19.jar) 
UCHIJA	dsurround{3.3.3.1} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.3.3.1.jar) 

```
java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.WorldProvider.getSunBrightnessFactor(WorldProvider.java:399)
	at org.blockartistry.mod.DynSurround.util.DiurnalUtils.isSunrise(DiurnalUtils.java:47)
	at org.blockartistry.mod.DynSurround.util.DiurnalUtils.isAuroraInvisible(DiurnalUtils.java:68)
	at org.blockartistry.mod.DynSurround.util.DiurnalUtils.isAuroraVisible(DiurnalUtils.java:64)
	at org.blockartistry.mod.DynSurround.client.handlers.ExpressionStateHandler$5.update(ExpressionStateHandler.java:158)
	at org.blockartistry.mod.DynSurround.client.handlers.ExpressionStateHandler.pre(ExpressionStateHandler.java:511)
	at org.blockartistry.mod.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:117)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1897_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by OreCruncher** [comment]
What dimension were you in?

**Comment by alex2069** [comment]
Standard over-world (dim 0? or whatever it is)

**Comment by alex2069** [comment]
While trying to debug it, I tested during night and day, and with and without an Aurora visible.

**Comment by OreCruncher** [comment]
Smells like Advanced Rocketry.  I will load it up in debug to see if I can narrow things down.

**Comment by alex2069** [comment]
Yea I imagine it's doing something weird - it's quite a buggy (alpha) mod with some very very weird UI issues sometimes.
Though the main point was that the Aurora check shouldn't be happening when it's disable on both client and server. I can live without Auroras; I use Optifine so they look weird unfortunately (having said that another user that doesn't use Optifine also crashes so it's unrelated), but I really miss the rest of this mod!

**Comment by OreCruncher** [comment]
Actually what Dynamic Surroundings is doing is collecting state information for it's script engine.  This info is used by scripts to trigger things like sounds.  This part of the logic doesn't do anything with aurora rendering.

**Comment by alex2069** [comment]
If it's not a quick fix (was hoping it was just something that wasn't checking if it they were disable) and you can't reproduce it let me know and I'll try to isolate it on my end (dreading this - might be so many mod interactions x.x).

**Comment by OreCruncher** [comment]
I loaded up the AR mod in my dev environment (minimal mods) and didn't have a problem.  I will take a look at Beyond - it's a conflict somewhere.

**Comment by OreCruncher** [comment]
I am not able to duplicate.  Added additional code to ensure that Dynamic Surroundings does not operate on a null provider object based on the callstack provided.  If the problem continues to occur then I suggest opening an issue with Advanced Rocketry.

**Comment by OreCruncher** [comment]
Pushed update to CurseForge that I hope will address the problem.
