### ISSUE TITLE
[1.11.2] Dynamic surrounding hangs minecraft and gives message of crash

### ISSUE THREAD

**Issue by teutates1989** [OreCruncher/DynamicSurroundings#122]
*Mod Version:*
DynamicSurroundings-1.11.2-3.4.5.6

*Forge Version:*

forge-13.20.0.2315

*Link to crash log (if applicable):*

[19:50:44] [Thread-31/INFO]: [STDERR]: java.lang.NullPointerException
[19:50:44] [Thread-31/INFO]: [STDERR]: 	at paulscode.sound.codecs.CodecJOrbis.readBytes(CodecJOrbis.java:643)
[19:50:44] [Thread-31/INFO]: [STDERR]: 	at paulscode.sound.codecs.CodecJOrbis.read(CodecJOrbis.java:356)
[19:50:44] [Thread-31/INFO]: [STDERR]: 	at paulscode.sound.Source.stream(Source.java:953)
[19:50:44] [Thread-31/INFO]: [STDERR]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
[19:50:47] [Client thread/INFO]: [CHAT] It looks like the sound system has crashed.
[19:50:47] [Client thread/INFO]: [CHAT] Attempting to restart...
[19:50:47] [Client thread/WARN]: It looks like the sound system has crashed.
[19:50:47] [Client thread/WARN]: Attempting to restart...
[19:50:47] [Client thread/WARN]: Missing sound for event: voidcraft:spectrechain.chainlive
[19:50:47] [Client thread/INFO]: SoundSystem shutting down...
[19:50:52] [Client thread/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[19:50:52] [Client thread/ERROR]: Stream thread did not die!
[19:50:52] [Client thread/INFO]: Ignoring errors... continuing clean-up.
[19:50:52] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[19:50:52] [Sound Library Loader/INFO]: Starting up SoundSystem...
[19:50:52] [Thread-69/INFO]: Initializing LWJGL OpenAL
[19:50:52] [Thread-69/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[19:50:52] [Thread-69/INFO]: OpenAL initialized.
[19:50:52] [Sound Library Loader/INFO]: Sound engine started

*Description:*

Minecraft hangs for a few seconds and then gets this in chat..
[19:50:47] [Client thread/INFO]: [CHAT] It looks like the sound system has crashed.
[19:50:47] [Client thread/INFO]: [CHAT] Attempting to restart...

**Comment by OreCruncher** [comment]
I am beginning to regret adding restart capability.  Read up on it here: https://www.reddit.com/r/feedthebeast/comments/6j83g8/sprout_modpack_sound_system/djm560i/

**Comment by TomberWolf** [comment]
So, no solution. Just using no sounds??

**Comment by OreCruncher** [comment]
The two choices are:

* Disable the auto-restart.  When the streaming sound handler crashes you will no longer get streaming sounds (Minecraft music, Dynamic Surroundings biome sounds, Ambient Music Sounds, or streaming sounds from any other mod).

* Leave it enabled and occasionally get client side lag spikes because of the sound system reloading.  The amount of lag is very much dependent on the modpack.

This bug is down in a 3rd party library that I have no control over.  CreativeMD and I have been working the issue.  He contacted the author of the library and the author is aware.  What happens at this point waits to be seen.
