### ISSUE TITLE
game hangs when i try to eat stuff

### ISSUE THREAD

**Issue by AsteroidzX** [OreCruncher/DynamicSurroundings#133]
*Mod Version:*1.12-3.4.6.0

*Forge Version:*1.12-14.21.1.2387

*Link to crash log (if applicable):*ther isent any crashing involved

*Description:*when ever i try to eat any type of food, my game hangs, doesent crash

**Comment by OreCruncher** [comment]
What mod pack?  And how long did you wait?

**Comment by AsteroidzX** [comment]
its a bundel of mods i chose, heres the list of them:

BetterFoliage
Blur
CreativeCore
CrossHairMod
DurabilityShow
DynamicSurroundings
ItemsPhysic
Optifine
ShoulderSurfing
ToroHealth

i know that ShoulderSurfing mod cusases that proplem too, but nobody really reported it as an issue, so i did, and i didint really wait to see how long my game would last hung.

**Comment by AsteroidzX** [comment]
ok, this is the latest log from when my game crashes

 

[11:50:06] [main/INFO]: Setting user: ?????
[11:50:07] [main/INFO]: [STDOUT]: [itemphysic] Patched net.minecraft.entity.item.EntityItem ...
[11:50:07] [main/INFO]: [STDOUT]: [itemphysic] Patched net.minecraft.entity.item.EntityItem ...
[11:50:17] [main/INFO]: [STDOUT]: [creativecore] Patched net.minecraft.world.chunk.Chunk ...
[11:50:18] [main/WARN]: Skipping bad option: lastServer:
[11:50:19] [main/INFO]: LWJGL Version: 2.9.4
[11:50:28] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Better Foliage, FMLFileResourcePack:Blur, FMLFileResourcePack:CreativeCore, FMLFileResourcePack:Custom Crosshair Mod, FMLFileResourcePack:Durability Show, FMLFileResourcePack:Dynamic Surroundings, FMLFileResourcePack:Presets!, FMLFileResourcePack:Shoulder Surfing, FMLFileResourcePack:ToroHealth Damage Indicators, Better Foliage generated, Blur dummy resource pack, additional-elytras-tron-update-1497983847.zip, Odyssey.zip
[11:50:31] [main/INFO]: [STDERR]: org.lwjgl.LWJGLException: Could not locate OpenAL library.
[11:50:31] [main/INFO]: [STDERR]: at org.lwjgl.openal.AL.create(AL.java:156)
[11:50:31] [main/INFO]: [STDERR]: at org.lwjgl.openal.AL.create(AL.java:102)
[11:50:31] [main/INFO]: [STDERR]: at org.lwjgl.openal.AL.create(AL.java:206)
[11:50:31] [main/INFO]: [STDERR]: at org.blockartistry.DynSurround.client.sound.SoundEngine.configureSound(SoundEngine.java:178)
[11:50:31] [main/INFO]: [STDERR]: at org.blockartistry.DynSurround.client.sound.SoundEngine.onSoundSetup(SoundEngine.java:162)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_SoundEngine_onSoundSetup_SoundSetupEvent.invoke(.dynamic)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraft.client.audio.SoundManager.<init>(SoundManager.java:79)
[11:50:31] [main/INFO]: [STDERR]: at org.blockartistry.DynSurround.client.sound.SoundManagerReplacement.<init>(SoundManagerReplacement.java:90)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraft.client.audio.SoundHandler.<init>(SourceFile:71)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:472)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraft.client.main.Main.main(SourceFile:123)
[11:50:31] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:50:31] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:50:31] [main/INFO]: [STDERR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:50:31] [main/INFO]: [STDERR]: at java.lang.reflect.Method.invoke(Method.java:483)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[11:50:31] [main/INFO]: [STDERR]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:50:32] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:50:33] [Thread-6/INFO]: Initializing LWJGL OpenAL
[11:50:33] [Thread-6/INFO]: (The LWJGL binding of OpenAL. For more information, see http://www.lwjgl.org)
[11:50:38] [main/ERROR]: Unable to parse metadata from minecraft:textures/blocks/i_golden_shovel.png
java.lang.RuntimeException: broken aspect ratio and not an animation
at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_188538_a(TextureAtlasSprite.java:343) ~[cdo.class:?]
at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:227) [cdn.class:?]
at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:149) [cdn.class:?]
at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168) [ModelLoader.class:?]
at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cga.class:?]
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cet.class:?]
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bhz.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bhz.class:?]
at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:50:38] [main/ERROR]: Using missing texture, unable to load minecraft:textures/items/wooden_hoe.png, java.io.FileNotFoundException
[11:50:38] [main/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/texture.png, java.io.FileNotFoundException
[11:50:38] [main/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/planks birch/.13.png, java.io.FileNotFoundException
[11:50:38] [main/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/planks birch/.17.png, java.io.FileNotFoundException
[11:50:38] [main/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/planks birch/.21.png, java.io.FileNotFoundException
[11:50:38] [main/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/planks birch/.25.png, java.io.FileNotFoundException
[11:50:38] [main/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/noteblock/44.png, java.io.EOFException
[11:50:38] [main/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/particle.png, java.io.FileNotFoundException
[11:50:39] [main/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/e_texture.png, java.io.FileNotFoundException
[11:50:39] [main/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/cit/custom elytras/mario wings/lotus_wings_broken_icon.png, java.io.FileNotFoundException
[11:50:39] [main/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/4.png, java.io.FileNotFoundException
[11:50:39] [main/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/cit/custom elytras/mario wings/lotus_wings_icon.png, java.io.FileNotFoundException
[11:50:39] [Thread-6/INFO]: OpenAL initialized.
[11:50:39] [Sound Library Loader/INFO]: Sound engine started
[11:50:40] [main/INFO]: Created: 8192x4096 textures-atlas
[11:50:51] [main/INFO]: [STDOUT]: [itemphysic] Patched net.minecraft.client.renderer.entity.RenderEntityItem ...
[11:50:53] [main/WARN]: Skipping bad option: lastServer:
[11:50:53] [main/INFO]: Narrator library for x64 successfully loaded
[11:51:43] [Server thread/INFO]: Starting integrated minecraft server version 1.12
[11:51:43] [Server thread/INFO]: Generating keypair
[11:51:45] [Server thread/INFO]: Loaded 488 advancements
[11:51:45] [Server thread/INFO]: Preparing start region for level 0
[11:51:46] [Server thread/INFO]: Preparing spawn area: 0%
[11:51:46] [Server thread/WARN]: Keeping entity minecraft:chicken that already exists with UUID 7069479e-4a88-434f-899d-fcf3825f5373
[11:51:47] [Server thread/WARN]: Keeping entity minecraft:chicken that already exists with UUID 45dc0783-91e6-43ab-9829-a62993c51a20
[11:51:47] [Server thread/INFO]: Preparing spawn area: 47%
[11:51:47] [Server thread/WARN]: Keeping entity minecraft:sheep that already exists with UUID 36de5a81-fd27-4df7-8967-5f966b8344cc
[11:51:48] [Server thread/WARN]: Keeping entity minecraft:llama that already exists with UUID d74d7a64-38c9-481e-8304-21c410ad76a0
[11:51:48] [Server thread/INFO]: Preparing spawn area: 99%
[11:51:48] [Server thread/INFO]: Changing view distance to 8, from 10
[11:51:52] [Server thread/INFO]: ??????[local:E:3f5a48a1] logged in with entity id 323 at (-539.6764677787564, 110.0, 56.607451559016596)
[11:51:52] [Server thread/INFO]: ????? land to this planet
[11:51:56] [Server thread/INFO]: Saving and pausing game...
[11:51:58] [Server thread/INFO]: Saving chunks for level 'test'/overworld
[11:51:58] [main/INFO]: Loaded 155 advancements
[11:51:58] [Server thread/INFO]: Saving chunks for level 'test'/the_nether
[11:51:58] [Server thread/INFO]: Saving chunks for level 'test'/the_end
[11:51:58] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2570ms behind, skipping 51 tick(s)

 

idk why that last line happens, its proabebly the cuse of my game crashing ?

**Comment by OreCruncher** [comment]
The last line is telling you that the server is experiencing lag related problems.  What is interesting is the following"
```
[11:50:31] [main/INFO]: [STDERR]: org.lwjgl.LWJGLException: Could not locate OpenAL library.
```
I have seen this sporadically show up for some unknown reason.  Do you think your Minecraft installation is "sane"?

**Comment by OreCruncher** [comment]
@AsteroidzX Have you updated Forge?  Are you still experiencing the problem?

**Comment by AsteroidzX** [comment]
soory soory, i wasent off for quite a while, really soory for the late responce

yes, i have moved to the "reccomended" version and "lateset" version multiple times, i still get the same problem

**Comment by OreCruncher** [comment]
Have you tried removing some of the other mods till it stops?  I am currently running the Radon modpack with some other folks and no one is reporting this issue.

**Comment by AsteroidzX** [comment]
i only used your mod and it still gave me the same problem

**Comment by OreCruncher** [comment]
Can you post a complete client log using only my mod?  Reason is that I can't duplicate and I am hoping that there is something more specific in the log that will give me clues.  Also, what launcher are you using?

**Comment by AsteroidzX** [comment]
normal minecraft luncher, why ?

**Comment by AsteroidzX** [comment]
[17:45:49] [main/INFO]: Setting user: CybernetricKat
[17:45:58] [main/WARN]: Skipping bad option: lastServer:
[17:45:58] [main/INFO]: LWJGL Version: 2.9.4
[17:46:07] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Dynamic Surroundings, FMLFileResourcePack:Presets!
[17:46:27] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:46:27] [Thread-6/INFO]: Initializing LWJGL OpenAL
[17:46:27] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:46:28] [Thread-6/INFO]: OpenAL initialized.
[17:46:28] [Sound Library Loader/INFO]: Sound engine started
[17:46:37] [main/INFO]: Created: 512x512 textures-atlas
[17:46:42] [main/WARN]: Skipping bad option: lastServer:
[17:46:42] [main/INFO]: Narrator library for x64 successfully loaded
[17:49:03] [Server thread/INFO]: Starting integrated minecraft server version 1.12
[17:49:03] [Server thread/INFO]: Generating keypair
[17:49:05] [Server thread/INFO]: Loaded 488 advancements
[17:49:05] [Server thread/INFO]: Preparing start region for level 0
[17:49:07] [Server thread/INFO]: Preparing spawn area: 0%
[17:49:07] [Server thread/WARN]: Keeping entity minecraft:chicken that already exists with UUID 7069479e-4a88-434f-899d-fcf3825f5373
[17:49:07] [Server thread/WARN]: Keeping entity minecraft:chicken that already exists with UUID 45dc0783-91e6-43ab-9829-a62993c51a20
[17:49:08] [Server thread/INFO]: Preparing spawn area: 44%
[17:49:08] [Server thread/WARN]: Keeping entity minecraft:sheep that already exists with UUID 36de5a81-fd27-4df7-8967-5f966b8344cc
[17:49:09] [Server thread/WARN]: Keeping entity minecraft:llama that already exists with UUID d74d7a64-38c9-481e-8304-21c410ad76a0
[17:49:09] [Server thread/INFO]: Preparing spawn area: 99%
[17:49:09] [Server thread/INFO]: Changing view distance to 8, from 10
[17:49:14] [Server thread/INFO]: CybernetricKat[local:E:ce99c4e6] logged in with entity id 397 at (-189.5, 67.0, 258.5)
[17:49:14] [Server thread/INFO]: CybernetricKat joined the game
[17:49:17] [Server thread/INFO]: Saving and pausing game...
[17:49:17] [Server thread/INFO]: Saving chunks for level 'test'/overworld
[17:49:17] [Server thread/INFO]: Saving chunks for level 'test'/the_nether
[17:49:17] [Server thread/INFO]: Saving chunks for level 'test'/the_end
[17:49:18] [main/INFO]: Loaded 155 advancements
[17:49:43] [Server thread/INFO]: [CybernetricKat: Set own game mode to Survival Mode]
[17:49:43] [main/INFO]: [CHAT] Your game mode has been updated to Survival Mode

heres the log, its not showing what happens after i eat something for some reason

**Comment by AsteroidzX** [comment]
[17:45:49] [main/INFO]: Setting user: ????
[17:45:58] [main/WARN]: Skipping bad option: lastServer:
[17:45:58] [main/INFO]: LWJGL Version: 2.9.4
[17:46:07] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Dynamic Surroundings, FMLFileResourcePack:Presets!
[17:46:27] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:46:27] [Thread-6/INFO]: Initializing LWJGL OpenAL
[17:46:27] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:46:28] [Thread-6/INFO]: OpenAL initialized.
[17:46:28] [Sound Library Loader/INFO]: Sound engine started
[17:46:37] [main/INFO]: Created: 512x512 textures-atlas
[17:46:42] [main/WARN]: Skipping bad option: lastServer:
[17:46:42] [main/INFO]: Narrator library for x64 successfully loaded
[17:49:03] [Server thread/INFO]: Starting integrated minecraft server version 1.12
[17:49:03] [Server thread/INFO]: Generating keypair
[17:49:05] [Server thread/INFO]: Loaded 488 advancements
[17:49:05] [Server thread/INFO]: Preparing start region for level 0
[17:49:07] [Server thread/INFO]: Preparing spawn area: 0%
[17:49:07] [Server thread/WARN]: Keeping entity minecraft:chicken that already exists with UUID 7069479e-4a88-434f-899d-fcf3825f5373
[17:49:07] [Server thread/WARN]: Keeping entity minecraft:chicken that already exists with UUID 45dc0783-91e6-43ab-9829-a62993c51a20
[17:49:08] [Server thread/INFO]: Preparing spawn area: 44%
[17:49:08] [Server thread/WARN]: Keeping entity minecraft:sheep that already exists with UUID 36de5a81-fd27-4df7-8967-5f966b8344cc
[17:49:09] [Server thread/WARN]: Keeping entity minecraft:llama that already exists with UUID d74d7a64-38c9-481e-8304-21c410ad76a0
[17:49:09] [Server thread/INFO]: Preparing spawn area: 99%
[17:49:09] [Server thread/INFO]: Changing view distance to 8, from 10
[17:49:14] [Server thread/INFO]: ????[local:E:ce99c4e6] logged in with entity id 397 at (-189.5, 67.0, 258.5)
[17:49:14] [Server thread/INFO]: ???? joined the game
[17:49:17] [Server thread/INFO]: Saving and pausing game...
[17:49:17] [Server thread/INFO]: Saving chunks for level 'test'/overworld
[17:49:17] [Server thread/INFO]: Saving chunks for level 'test'/the_nether
[17:49:17] [Server thread/INFO]: Saving chunks for level 'test'/the_end
[17:49:18] [main/INFO]: Loaded 155 advancements
[17:49:43] [Server thread/INFO]: [????: Set own game mode to Survival Mode]
[17:49:43] [main/INFO]: [CHAT] Your game mode has been updated to Survival Mode

here it is, for some reason it doesent show what happens after i try to eat food

**Comment by OreCruncher** [comment]
@AsteroidzX I have been unable to repro the problem and I've been looking at the code and can't see where something like this would happen.  I've made a lot of changes with the latest BETAs related to the sound engine crash stuff and would like to know your experience with it.  If you could give it a try and let me know I would appreciate it.

**Comment by OreCruncher** [comment]
Closing due to inactivity.  If the problem persists let me know.  Thanks!
