### ISSUE TITLE
1.12.2 Sound System Crashes

### ISSUE THREAD

**Issue by mrgrim** [OreCruncher/DynamicSurroundings#164]
*Mod Version:*

3.4.7.2

*Forge Version:*

14.23.0.2493

*Link to crash log (if applicable):*

[01:03:07] [Thread-39/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[01:03:07] [Thread-39/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.jcraft.jorbis.Info.clear(Info.java:114)
[01:03:07] [Thread-39/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:229)
[01:03:07] [Thread-39/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.libraries.SourceLWJGLOpenAL.preLoad(SourceLWJGLOpenAL.java:687)
[01:03:07] [Thread-39/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.Source.stream(Source.java:928)
[01:03:07] [Thread-39/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
Exception in thread "Thread-39" [01:03:21] [main/INFO]: [CHAT] It looks like the sound system has crashed.

*Description:*

I also get on a slightly older version on 1.12.1. These happen fairly regularly, maybe every 10 minutes or so when flying around in creative mode, and the sound system appears to restart after without issue.

Let me know what else I can provide.

Thanks

**Comment by OreCruncher** [comment]
It's a PaulsCode bug.  See #152 for detail.  I have noticed this bug since 1.7.10.
