### ISSUE TITLE
Crash with other mods

### ISSUE THREAD

**Issue by JoKangHyeon** [OreCruncher/DynamicSurroundings#177]
*Mod Version:*
DynamicSurroundings-1.11.2-3.4.7.2
*Forge Version:*
1.11.2-forge1.11.2-13.20.1.2513

*Link to crash log (if applicable):*
java.lang.NullPointerException: Unexpected error
 at net.minecraft.world.WorldProvider.getSunBrightnessFactor(WorldProvider.java:407)
 at org.blockartistry.lib.DiurnalUtils.getCycle(DiurnalUtils.java:59)
 at org.blockartistry.lib.DiurnalUtils.isAuroraInvisible(DiurnalUtils.java:78)
 at org.blockartistry.lib.DiurnalUtils.isAuroraVisible(DiurnalUtils.java:74)
 at org.blockartistry.DynSurround.client.handlers.ExpressionStateHandler$5.update(ExpressionStateHandler.java:107)
 at org.blockartistry.DynSurround.client.handlers.ExpressionStateHandler.process(ExpressionStateHandler.java:515)
 at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:122)

*Description:*
some mod's world not uses some factors so sometimes game crashes.
(Sorry for my terrible english....)

**Comment by OreCruncher** [comment]
Seems the circumstance is strange.  The world property for the WorldProvider is null for some reason.  I am adding some defensive code so it doesn't crash.

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.
