### ISSUE TITLE
[1.10.2] Error on Server Side

### ISSUE THREAD

**Issue by MJRLegends** [OreCruncher/DynamicSurroundings#187]
*Mod Version:* 
3.4.7.2
*Forge Version:*
12.18.3.2511

*Description:*
When starting the server with Dynamic Surrondings, i seem to get this error below. Probably just needs defining as client side only code? maybe not sure off the top of my head from looking at the error.
```

[21:01:56] [Server thread/ERROR] [dsurround/dsurround]: Unable to process configuration script
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: java.lang.NoClassDefFoundError: org/blockartistry/DynSurround/client/handlers/scanners/BattleScanner
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.<clinit>(EnvironStateHandler.java:118)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.FakeBiome.getTrueBiome(FakeBiome.java:55)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.FakeBiome.func_76727_i(FakeBiome.java:90)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.BiomeInfo.getRainfall(BiomeInfo.java:212)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.BiomeMatcher$ConditionsImpl$2.asNumber(BiomeMatcher.java:151)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.BiomeMatcher$ConditionsImpl$2.compareTo(BiomeMatcher.java:146)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.BiomeMatcher$ConditionsImpl$2.compareTo(BiomeMatcher.java:143)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.lib.script.Expression$11.eval(Expression.java:149)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.lib.script.Expression$37.eval(Expression.java:597)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.lib.script.Expression$37.eval(Expression.java:597)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.lib.script.Expression.eval(Expression.java:636)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.BiomeMatcher$ConditionsImpl.match(BiomeMatcher.java:229)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.BiomeRegistry.register(BiomeRegistry.java:204)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.scripts.json.ConfigurationScript.process(ConfigurationScript.java:102)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.scripts.JsonScriptingEngine.eval(JsonScriptingEngine.java:66)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.DataScripts.runFromArchive(DataScripts.java:108)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.DataScripts.execute(DataScripts.java:70)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.RegistryManager.reload(RegistryManager.java:134)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.RegistryManager.getRegistry(RegistryManager.java:147)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.registry.RegistryManager.get(RegistryManager.java:72)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.server.services.ServiceManager.<init>(ServiceManager.java:55)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.server.services.ServiceManager.<clinit>(ServiceManager.java:52)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.proxy.Proxy.serverAboutToStart(Proxy.java:98)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.DSurround.serverAboutToStart(DSurround.java:221)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:01:56] [Server thread/INFO] [STDERR/dsurround]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

MJRLegends

**Comment by OreCruncher** [comment]
Not entirely sure.  Will need to do some digging.

**Comment by OreCruncher** [comment]
First thing the error isn't a problem for a dedicated server because none of the biome registry stuff is used for pure server operation.  The issue is that the battle music logic is client side only, but the underlying script engine I have wants to use some of that data thus the exception is triggered.  I need to figure out how to untie this knot just so the exception goes away.

**Comment by MJRLegends** [comment]
Nice work :D

**Comment by OreCruncher** [comment]
Pushed v3.4.8.0 with fixes.

**Comment by MJRLegends** [comment]
Great thank you
