### ISSUE TITLE
Client crash while transferring to a vanilla hub

### ISSUE THREAD

**Issue by LemADEC** [OreCruncher/DynamicSurroundings#21]
As of DynamicSurroundings-1.10.2-3.1.4.1.jar, I had a crash while the modded server was rebooting, transfering my client to a vanilla hub:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  ForgelinPlugin (Forgelin-1.2.0.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  llibrary (llibrary-1.7.2-1.10.2.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.1.4.1.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  IvToolkit (IvToolkit-1.2.9.jar)
  OpenEyePlugin (OpenEye-1.10.2-0.8.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
  literalascension (literalascension-1.10.2-1.0.0.3.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 06/01/17 01:14
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at org.blockartistry.mod.DynSurround.client.handlers.AreaSoundEffectHandler.process(AreaSoundEffectHandler.java:90)
	at org.blockartistry.mod.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:131)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_622_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.blockartistry.mod.DynSurround.client.handlers.AreaSoundEffectHandler.process(AreaSoundEffectHandler.java:90)
	at org.blockartistry.mod.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:131)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_622_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['LemADEC'/964, l='MpServer', x=-1090,50, y=35,00, z=519,50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1091,35,519), Chunk: (at 13,2,7 in -69,32; contains blocks -1104,0,512 to -1089,255,527), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Level time: 971154135 game time, 5766000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 4 total; [EntityOtherPlayerMP['Monkey1357'/35, l='MpServer', x=-1090,50, y=35,00, z=519,50], EntityArmorStand['§b Welcome to Fun Square Games Hub§l'/8, l='MpServer', x=-1079,30, y=41,68, z=519,51], EntityArmorStand['§bCome see what's going on in Steve's head!'/9, l='MpServer', x=-1079,30, y=40,68, z=519,54], EntityPlayerSP['LemADEC'/964, l='MpServer', x=-1090,50, y=35,00, z=519,50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.11-SNAPSHOT:3ee7fdd:1212) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1651678032 bytes (1575 MB) / 3151495168 bytes (3005 MB) up to 3151495168 bytes (3005 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2202 86 mods loaded, 86 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJA	Forge{12.18.3.2202} [Minecraft Forge] (modpack.jar) 
	UCHIJA	ivtoolkit{1.2.9} [IvToolkit] (minecraft.jar) 
	UCHIJA	OpenEye{0.8} [OpenEye] (OpenEye-1.10.2-0.8.jar) 
	UCHIJA	backpacks16840{3.1.5} [Backpacks!] (zz-backpacks 1.10.2 - 3.1.5.jar) 
	UCHIJA	slimecompendium{1.4} [Slime Compendium] ([1.10.2]SlimeCompendium1.4.jar) 
	UCHIJA	movillages{1.5.2} [Mo' Villages] ([1.9.4]Mo' Villages-1.5.2.jar) 
	UCHIJA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJA	JEI{3.14.2.401} [Just Enough Items] (jei_1.10.2-3.14.2.401.jar) 
	UCHIJA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJA	aquaculture{1.4.0} [Aquaculture] (Aquaculture-1.10.2-1.4.0.28.jar) 
	UCHIJA	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHIJA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	AutoSapling{1.3.3} [AutoSapling] (Autosapling-1.3.3-MC1.10.jar) 
	UCHIJA	BetterAchievements{0.3.2.39} [Better Achievements] (BetterAchievements-1.10.2-0.3.2.39.jar) 
	UCHIJA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UCHIJA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJA	ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter-1.10.2-2.5.6.jar) 
	UCHIJA	coralreef{1.0} [Coral Reef] (CoralReef-1.2.jar) 
	UCHIJA	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJA	crocoduck{1.0} [Crocoducks] (Crocoducks-1.1.jar) 
	UCHIJA	dailies{1.10.2-6} [Bailey's Dailies] (dailies-1.10.2-6.jar) 
	UCHIJA	deathquotes{1.0.1} [Death Quotes] (DeathQuotes-1.0.1-mc1.9to1.10.2-forge.jar) 
	UCHIJA	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCHIJA	druidry{2016.9.26-1.9.4} [§2Druidry] (druidry(2016.9.26)(1.9.4).jar) 
	UCHIJA	dsurround{3.1.4.1} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.1.4.1.jar) 
	UCHIJA	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHIJA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJA	golems{6.02} [Extra Golems] (ExtraGolems[1.10.2]-6.02.jar) 
	UCHIJA	fw{1.3.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.3.0b.jar) 
	UCHIJA	glasscraftmod{2.0} [Glasscraft] (Glasscraftmod v1.01 - MC1.10.2 Forge.jar) 
	UCHIJA	helpfixer{1.0} [HelpFixer] (HelpFixer-1.10.2-1.4.15.jar) 
	UCHIJA	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHIJA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJA	immersiveengineering{0.10-54} [Immersive Engineering] (ImmersiveEngineering-0.10-54.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	itemscroller{0.8.0} [Item Scroller] (itemscroller-1.10.2-0.8.0.jar) 
	UCHIJA	journeymap{1.10.2-5.4.0} [JourneyMap] (journeymap-1.10.2-5.4.0.jar) 
	UCHIJA	justenoughbuttons{1.10.2-1.6.5} [Just Enough Buttons] (justenoughbuttons-1.10.2-1.6.5.jar) 
	UCHIJA	levels{r4.1.3} [Levels] (Levels-1.10.2-r4.1.3.jar) 
	UCHIJA	llibrary{1.7.2} [LLibrary] (llibrary-1.7.2-1.10.2.jar) 
	UCHIJA	literalascension{1.10.2-1.0.0.3} [Literal Ascension] (literalascension-1.10.2-1.0.0.3.jar) 
	UCHIJA	malisiscore{1.10.2-4.2.9} [MalisisCore] (malisiscore-1.10.2-4.2.9.jar) 
	UCHIJA	malisisdoors{1.10.2-5.1.6} [MalisisDoors] (malisisdoors-1.10.2-5.1.6.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJA	mowziesmobs{1.3.0} [Mowzie's Mobs] (mowziesmobs-1.3.0.jar) 
	UCHIJA	nethermetals{1.1.2} [Nether Metals] (NetherMetals_1.9-1.1.2.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJA	nmsot{1.2.0-mc1.10.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.10.2.jar) 
	UCHIJA	omlib{1.10.2-3.0.0-37} [OMLib] (omlib-1.10.2-3.0.0-37.jar) 
	UCHIJA	openmodularturrets{1.10.2-3.0.0-42} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-42.jar) 
	UCHIJA	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJA	ping{1.2.2} [Ping] (Ping-1.10.X-1.2.2.B7-universal.jar) 
	UCHIJA	shetiphiancore{3.3.6} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.6.jar) 
	UCHIJA	platforms{1.2.7} [Platforms] (platforms-1.10.0-1.2.7.jar) 
	UCHIJA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJA	reccomplex{1.2.4} [Recurrent Complex] (RecurrentComplex-1.2.4.jar) 
	UCHIJA	reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-58.jar) 
	UCHIJA	Roguelike{1.5.5} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.5.jar) 
	UCHIJA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJA	runesofwizardry{1.10.2-0.7.2} [Runes of Wizardry] (Runes-of-Wizardry-1.10.2-0.7.2.jar) 
	UCHIJA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJA	SilentLib{1.1.0} [Silent Lib] (SilentLib-1.10.2-1.1.0-23.jar) 
	UCHIJA	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UCHIJA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJA	spartanshields{1.1c} [Spartan Shields] (SpartanShields-1.10.2-1.1c.jar) 
	UCHIJA	squarebuckets{1.01} [Square Buckets] (squarebuckets-1.01_MC-1.10.2.jar) 
	UCHIJA	squarethecircle{1.00} [Square the Circle] (squarebuckets-1.01_MC-1.10.2.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.5.16} [Storage Drawers] (StorageDrawers-1.10.2-3.5.16.jar) 
	UCHIJA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJA	terraincontrol{2.8.2-SNAPSHOT} [TerrainControl] (terraincontrol-forge-2.8.2-1.10.2-B1.jar) 
	UCHIJA	totemic{1.9.4-0.7.9.1} [Totemic] (Totemic-1.9.4-0.7.9.1.jar) 
	UCHIJA	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJA	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	waterstrainer{1.3.2} [Water Strainer] (WaterStrainer-1.9.4-1.3.2.jar) 
	UCHIJA	YALSM{2.1.6} [Yet Another Leather Smelting Mod] (yalsm-2.1.6-mc1.9.4.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
ForgelinPlugin (Forgelin-1.2.0.jar)
  
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
llibrary (llibrary-1.7.2-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.1.4.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  shetiphian.core.asm.ClassTransformer
IvToolkit (IvToolkit-1.2.9.jar)
  
OpenEyePlugin (OpenEye-1.10.2-0.8.jar)
  openeye.asm.MultiTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
  brad16840.common.asm.ClassTransformer
literalascension (literalascension-1.10.2-1.0.0.3.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4474' Renderer: 'Intel(R) HD Graphics 530'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2202
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 20.19.15.4474, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
```

**Comment by OreCruncher** [comment]
How repeatable is it?

**Comment by OreCruncher** [comment]
OK.  I think I know what is happening.  Turns out the connect event fires on a Netty thread, not the client thread.  My theory is that the client thread starts ticking before the connect event is finished so the underlying system is half initialized.  The sound manager hasn't been created yet (occuring in Netty thread) while the client thread is ticking away.

**Comment by OreCruncher** [comment]
Pushed release with fix to CurseForge.
