### ISSUE TITLE
Stack Trace when BattleScanner not installed

### ISSUE THREAD

**Issue by iamtpage** [OreCruncher/DynamicSurroundings#216]
*Mod Version:* DynamicSurroundings-1.12.2-3.4.7.2

*Forge Version:* forge-1.12.2-14.23.1.2555-universal-server

*Link to crash log (if applicable):*
```
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: java.lang.NoClassDefFoundError: org/blockartistry/DynSurround/client/handlers/scanners/BattleScanner
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.<clinit>(EnvironStateHandler.java:118)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.FakeBiome.getTrueBiome(FakeBiome.java:58)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.FakeBiome.func_76727_i(FakeBiome.java:93)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.BiomeInfo.getRainfall(BiomeInfo.java:238)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.BiomeMatcher$ConditionsImpl$2.asNumber(BiomeMatcher.java:157)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.BiomeMatcher$ConditionsImpl$2.compareTo(BiomeMatcher.java:152)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.BiomeMatcher$ConditionsImpl$2.compareTo(BiomeMatcher.java:149)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.lib.script.Expression$11.eval(Expression.java:149)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.lib.script.Expression$37.eval(Expression.java:597)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.lib.script.Expression$37.eval(Expression.java:597)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.lib.script.Expression.eval(Expression.java:636)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.BiomeMatcher$ConditionsImpl.match(BiomeMatcher.java:245)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.BiomeRegistry.register(BiomeRegistry.java:184)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.scripts.json.ConfigurationScript.process(ConfigurationScript.java:101)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.scripts.JsonScriptingEngine.eval(JsonScriptingEngine.java:66)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.DataScripts.runFromArchive(DataScripts.java:108)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.DataScripts.execute(DataScripts.java:70)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.RegistryManager.reload(RegistryManager.java:134)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.RegistryManager.getRegistry(RegistryManager.java:147)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.registry.RegistryManager.get(RegistryManager.java:72)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.server.services.ServiceManager.<init>(ServiceManager.java:55)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.server.services.ServiceManager.<clinit>(ServiceManager.java:52)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.proxy.Proxy.serverAboutToStart(Proxy.java:98)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at org.blockartistry.DynSurround.DSurround.serverAboutToStart(DSurround.java:229)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at java.lang.reflect.Method.invoke(Method.java:498)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at java.lang.reflect.Method.invoke(Method.java:498)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at java.lang.reflect.Method.invoke(Method.java:498)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:840)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:290)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:268)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
> [07:12:05] [Server thread/INFO] [STDERR]: [org.blockartistry.lib.logging.ModLog:error:109]: at java.lang.Thread.run(Thread.java:748)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: org.blockartistry.DynSurround.client.handlers.scanners.BattleScanner
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: ... 59 more
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@5f14a673 from coremod FMLCorePlugin
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: ... 61 more
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.RuntimeException: Attempted to load class org/blockartistry/DynSurround/client/handlers/scanners/BattleScanner for invalid side SERVER
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
> [07:12:05] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: ... 63 more
```
*Description:*
Shows up every time the server boots, it seems like its searching for a mod called "Battle Scanner"

**Comment by OreCruncher** [comment]
Actually Battle Scanner is part of Dynamic Surroundings.  It's client side and scans the area around the player looking for attacking mobs so that battle music can trigger.

This is fixed in the latest BETAs.  I believe you can drop the BETA jar server side and not update the clients.

**Comment by iamtpage** [comment]
How stable is the latest BETAs? Is it going to be a while before the next stable release?

**Comment by OreCruncher** [comment]
Should be stable.  As it relates to changes no changes are being made to the server side code.  The work is pretty much client side code.  As for RELEASE I am not entirely sure.  There will be another BETA drop here in the next few days, and feedback on that BETA will drive the RELEASE date.

**Comment by iamtpage** [comment]
Okay, I'll test with the latest BETA and report back

**Comment by OreCruncher** [comment]
@iamtpage Have you had a change to check it out?

**Comment by iamtpage** [comment]
Sorry, life got in the way. I'll be able to check tomorrow.

**Comment by iamtpage** [comment]
Rebooted a few times, no stack trace. This issue can be closed

**Comment by OreCruncher** [comment]
Cool!  Thanks!
