### ISSUE TITLE
Crash ConcurrentModificationException

### ISSUE THREAD

**Issue by StefanHirche** [OreCruncher/DynamicSurroundings#262]
*Mod Version:* DynamicSurroundings-1.12.2-3.4.8.2.jar

*Forge Version:*  Forge 14.23.1.2555 

*Link to crash log (if applicable):*
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.blockartistry.DynSurround.client.hud.PotionHUD.doRender(PotionHUD.java:213)
	at org.blockartistry.DynSurround.client.hud.GuiHUDHandler.onRenderGameOverlayEvent(GuiHUDHandler.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_292_GuiHUDHandler_onRenderGameOverlayEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:900)
	at net.minecraftforge.client.GuiIngameForge.renderPotionIcons(GuiIngameForge.java:225)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:174)

*Description:*
Game crashed. As my son just played, I don't know what happened. But as he told me this occurred several times.

**Comment by OreCruncher** [comment]
Is the modpack available online?

**Comment by StefanHirche** [comment]
Hi,
it's just a list of mods I collected on my own.
I will use a newer version, should have been my first approach.
You will get a complete log if this will occur again, as I did not keep it.

Could you tell me by this trace what I could test in special to reproduce this issue?

**Comment by OreCruncher** [comment]
No specific test really.  What it would require is knowing which mod is causing the problem, and then getting it to generate a sound at the same time Minecraft is updating it's internal sound list.  Not something you can do blackbox.

**Comment by OreCruncher** [comment]
@StefanHirche Hey!  Have you had a chance to check out an updated version?

**Comment by OreCruncher** [comment]
Closing due to inactivity.  If the issue still occurs feel free to reopen and supply the client log.  Thanks!
