### ISSUE TITLE
[OpenEye] NPE in EnvironStateHandler

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#267]
*Mod Version:*
1.12.2-3.4.9.6

```
java.lang.NullPointerException: 

    at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.tick(EnvironStateHandler.java:154)
    at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler$EnvironState.access$000(EnvironStateHandler.java:69)
    at org.blockartistry.DynSurround.client.handlers.EnvironStateHandler.process(EnvironStateHandler.java:385)
    at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:144)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_0_EffectManager_onTick_ClientTickEvent.invoke(.dynamic:-1)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by OreCruncher** [comment]
Pushed v3.4.9.7 to CurseForge.
