### ISSUE TITLE
[OpenEye] NoSuchFieldError: REACH_DISTANCE

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#268]
*Mod Version:*
1.12.2-3.4.9.6

*Forge Version:*
14.23.0.2491

```
java.lang.NoSuchFieldError: REACH_DISTANCE

    at org.blockartistry.lib.math.RayTrace.trace(RayTrace.java:66)
    at org.blockartistry.DynSurround.client.handlers.effects.EntitySwingEffect.update(EntitySwingEffect.java:75)
    at org.blockartistry.lib.effects.EntityEffectHandler.update(EntityEffectHandler.java:108)
    at org.blockartistry.DynSurround.client.handlers.FxHandler.lambda$static$1(FxHandler.java:86)
    at org.blockartistry.DynSurround.client.handlers.FxHandler$$Lambda$0/0.test(-1)
    at java.util.Collection.removeIf(Collection.java:414)
    at org.blockartistry.DynSurround.client.handlers.FxHandler.process(FxHandler.java:117)
    at org.blockartistry.DynSurround.client.handlers.EffectManager.onTick(EffectManager.java:144)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_0_EffectManager_onTick_ClientTickEvent.invoke(.dynamic:-1)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by OreCruncher** [comment]
Player should upgrade to the latest release version for 1.12.2.

**Comment by OreCruncher** [comment]
That version of Forge doesn't have the appropriate mappings.  Forge install needs to be 2555+.

**Comment by OreCruncher** [comment]
Pushed v3.4.9.7 to CurseForge.
