### ISSUE TITLE
[OpenEye] NPE doing a toString() on BasicSound

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#270]
*Mod Version:*
1.12.2-3.4.8.5

*Forge Version:*
14.23.1.2598

```
java.lang.NullPointerException: 

    at java.lang.String.length(-1)
    at java.lang.AbstractStringBuilder.append(-1)
    at java.lang.StringBuilder.append(-1)
    at java.lang.StringBuilder.append(-1)
    at com.google.common.base.MoreObjects$ToStringHelper.toString(MoreObjects.java:350)
    at org.blockartistry.DynSurround.client.sound.BasicSound.toString(BasicSound.java:277)
    at org.blockartistry.DynSurround.client.sound.Emitter.fade(Emitter.java:145)
    at org.blockartistry.DynSurround.client.handlers.SoundEffectHandler.queueAmbientSounds(SoundEffectHandler.java:173)
    at org.blockartistry.DynSurround.client.handlers.AreaSoundEffectHandler.process(AreaSoundEffectHandler.java:117)
    at org.blockartistry.DynSurround.client.handlers.EffectManager.playerTick(EffectManager.java:105)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_0_EffectManager_playerTick_PlayerTickEvent.invoke(.dynamic:-1)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:363)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)
    at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
    at net.minecraft.world.World.func_72866_a(World.java:1990)
    at net.minecraft.world.World.func_72870_g(World.java:1952)
    at net.minecraft.world.World.func_72939_s(World.java:1756)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by OreCruncher** [comment]
Looking at this I think it may have already been fixed.  Answer is to update to a newer version of the mod.
