### ISSUE TITLE
Conflict with OptiFine_1.12.2_HD_U_D1_pre.jar

### ISSUE THREAD

**Issue by Tsoccerguy3** [OreCruncher/DynamicSurroundings#282]
*Mod Version:*
1.12.2
*Forge Version:*
forge-1.12.2-14.23.2.2625-installer.jar

*Link to crash log (if applicable):*

*Description:*
https://github.com/sp614x/optifine/issues/1285
Crash on start. This is new development as of today , Most likely Optifine pre problem . No Crash logs.

http://optifine.net/adloadx?f=preview_OptiFine_1.12.2_HD_U_D1_pre.jar

**Comment by OreCruncher** [comment]
I assume it starts fine without OptiFine?

**Comment by Tsoccerguy3** [comment]
I used the latest release of DS with the latest Optifine D1 pre . instant crash with no logs .each wiill work on their own . spx614x is trying to enhance 1.12.2 D1 . optifine gets loaded first and DS crashes on trying to load . Tested with 50 mods each to see if any other conflicts . only crash with DS and the Optifine D1 pre. 

Most likely a Optifine problem , it gets loaded first and DS unable to figure out what Optifine has done

**Comment by OreCruncher** [comment]
Do you happen to know if it changed its mod ID?

**Comment by Tsoccerguy3** [comment]
IDK  , Optifine being closed source and hacky , you could extract the 2 mods 1.12.2 U C9 and U D1 pre to see if ID changed or forced debug.
Just reported to sp614x issue tracker . Just so he doesn’t go in wrong direction

**Comment by Tsoccerguy3** [comment]
`OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[15:47:25] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:47:25] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:47:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:47:25] [main/INFO] [FML]: Forge Mod Loader version 14.23.2.2625 for Minecraft 1.12.2 loading
[15:47:25] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_151, running on Linux:amd64:4.13.0-36-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[15:47:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in DynamicSurroundings-1.12.2-3.4.9.8.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:47:25] [main/WARN] [FML]: The coremod org.blockartistry.DynSurround.asm.TransformLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:47:25] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from preview_OptiFine_1.12.2_HD_U_D1_pre.jar
[15:47:25] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:47:25] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[15:47:25] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:47:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:47:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:47:25] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[15:47:25] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[15:47:25] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[15:47:25] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[15:47:25] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: /home/wds/.minecraft/mods/1.12.2/preview_OptiFine_1.12.2_HD_U_D1_pre.jar
[15:47:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:47:27] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:47:27] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:47:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:47:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:47:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:47:27] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:47:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:47:27] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[15:47:27] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:47:28] [main/INFO] [dsurround Transform]: Transmorgrifying [net.minecraft.world.WorldServer]: resetRainAndThunder
[15:47:28] [main/INFO] [dsurround Transform]: func_73051_P()V: Found!
[15:47:28] [main/INFO] [dsurround Transform]: Transmorgrified [net.minecraft.world.WorldServer]: resetRainAndThunder
[15:47:28] [main/INFO]: Setting user: MajorPayne181
[15:47:29] [main/INFO] [dsurround Transform]: Transmorgrifying [net.minecraft.entity.projectile.EntityArrow]: No Particles on Arrows
[15:47:29] [main/INFO] [dsurround Transform]: func_70071_h_()V: Found!
[15:47:29] [main/INFO] [dsurround Transform]: Transmorgrified [net.minecraft.entity.projectile.EntityArrow]: No Particles on Arrows
[15:47:31] [main/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[15:47:31] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[15:47:31] [main/INFO] [dsurround Transform]: Transmorgrifying [net.minecraft.client.renderer.EntityRenderer]: addRainParticles
[15:47:31] [main/INFO] [dsurround Transform]: func_78484_h()V: Found!
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: java.lang.RuntimeException: java.lang.SecurityException: class "bxy"'s signer information does not match signer information of other classes in the same package
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.objectweb.asm.ClassWriter.a(Unknown Source)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.objectweb.asm.Frame.a(Unknown Source)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.objectweb.asm.Frame.a(Unknown Source)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at org.blockartistry.lib.asm.MyTransformer.transform(MyTransformer.java:71)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at Reflector.<clinit>(Reflector.java:157)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.client.settings.GameSettings.setForgeKeybindProperties(GameSettings.java:3404)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.client.settings.GameSettings.<init>(GameSettings.java:303)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:443)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:47:31] [main/INFO] [STDERR]: [org.blockartistry.lib.asm.MyTransformer:transform:79]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:47:31] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class Reflector
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:138) ~[b.class:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) ~[b.class:?]
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:425) ~[b.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:381) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [15:47:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:47:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:47:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[15:47:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[15:47:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[15:47:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:47:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by Tsoccerguy3** [comment]
Forced debug in Linux Minecraft version , this will help

**Comment by OreCruncher** [comment]
That does help.  Wonder what OptiFine is doing.

**Comment by Tsoccerguy3** [comment]
Here is the Forge log . More details look on my Onedrive in the Ore directory
https://onedrive.live.com/?id=77B5E138E468EDE3%212070&cid=77B5E138E468EDE3

**Comment by Tsoccerguy3** [comment]
Issue fixed by sp614x  , closed

**Comment by OreCruncher** [comment]
Yay!  Thanks for checking.
