### ISSUE TITLE
Client crashes when using Vending blocks wrench

### ISSUE THREAD

**Issue by LemADEC** [OreCruncher/DynamicSurroundings#287]
*Mod Version:*
DynamicSurroundings-1.7.10-1.0.6.0.jar
*Forge Version:*
1.7.10-Forge10.13.4.1614-1.7.10

*Link to crash log (if applicable):*
https://gist.github.com/LemADEC/2f811a248785a3efa54706f9ff4a7160

*Description:*
Client crashes when using the Vending block's wrench on a vending machine.
The wrench is creative item to configure the block.

```
java.lang.NullPointerException: Updating screen events
	at org.blockartistry.mod.DynSurround.client.sound.SoundManagerReplacement.func_148611_c(SoundManagerReplacement.java:83)
	at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154)
	at info.jbcs.minecraft.vending.gui.GuiExButton.mouseDown(GuiExButton.java:77)
	at info.jbcs.minecraft.vending.gui.GuiElement.mouseDown(GuiElement.java:78)
	at info.jbcs.minecraft.vending.gui.GuiScreenPlus.func_146274_d(GuiScreenPlus.java:100)
	at info.jbcs.minecraft.vending.gui.GuiScreenPlus.func_146269_k(GuiScreenPlus.java:54)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by OreCruncher** [comment]
This is a weird error.  The underlying SoundManager data is in an inconsistent state.  Regardless, the maintenance update will change how the mod interacts with the Minecraft sound system.  It will either fix this error, or if it does occur it's outside of the DS execution path.

**Comment by OreCruncher** [comment]
Pushed v1.0.6.1 to CurseForge.  Let me know if the update changes things.
