### ISSUE TITLE
Crash with Forge 14.23.2.2635

### ISSUE THREAD

**Issue by MeinKraft** [OreCruncher/DynamicSurroundings#296]
*Mod Version:*
1.12.2-3.4.9.9
*Forge Version:*
14.23.2.2635

*Link to crash log (if applicable):*
https://pastebin.com/UwuEv58E

*Description:*
Run the MC Launcher with Forge 2635 and game crashes before title screen appears

**Comment by OreCruncher** [comment]
Yep - it would.  Back off to Forge 2634,  The finally merged in the sound engine fix yesterday.  I need to add some code to not do my sound patching.

**Comment by OreCruncher** [comment]
Remove ambient sounds to see if it works.  Reason is that I don't think it has been updated to take into account that Forge has this patch.  (AmbientSounds and Dynamic Surroundings uses the same patch that was integrated into Forge.)

**Comment by Tsoccerguy3** [comment]
yes it works without the AmbientSounds

**Comment by OreCruncher** [comment]
OK.  AmbientSounds needs to update.  The sound fix went into Forge yesterday. :)

**Comment by resinate** [comment]
im getting the crash with slimeknights in tinkers:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.9.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.12-93.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.5.5.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 3/25/18 6:37 PM
Description: Initializing game

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:35)
	at slimeknights.tconstruct.tools.ToolClientEvents.onModelBake(ToolClientEvents.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_715_ToolClientEvents_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by OreCruncher** [comment]
Not sure how that crash applies to Dynamic Surroundings.

**Comment by vpontin** [comment]
Good to know Forge have introduced a major (potentially breaking) feature. I updated my forge and all mods without know and now my installation is borked (same error).

**Comment by CreativeMD** [comment]
Actually I created this pr, we all knew about it. Just use an older forge version for now, until all the mods have fixed it (a fix for AmbientSounds has been uploaded already).

**Comment by vpontin** [comment]
A question: does "AmbientSounds" is embed on DS? Because i dont have it and still have the crash on b2635

**Comment by OreCruncher** [comment]
Assuming you didn't build DS yourself and are using the latest BETA from CurseForge, yes, it will crash irrespective of AmbientSounds.  That is what this issue is all about.  I have a fix in GitHub but it has not made it to CurseForge as of yet.

**Comment by vpontin** [comment]
Ok, will wait. thanks for your patience!

**Comment by OreCruncher** [comment]
No worries.  I plan to have a release tomorrow (Wednesday) assuming my testing holds.

**Comment by OreCruncher** [comment]
Pushed v.3.4.9.10 with the version detection code to apply the patch if needed.
