### ISSUE TITLE
crash game when creating a world, etc..

### ISSUE THREAD

**Issue by KiraLinux** [OreCruncher/DynamicSurroundings#310]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.9.11
*Forge Version:*
1.12.2-forge1.12.2-14.23.2.2654

*Link to crash log (if applicable):*
[crash.zip](https://github.com/OreCruncher/DynamicSurroundings/files/1905135/crash.zip)

*Description:*
crash game when creating a world or when approaching the generating village during the generation of a new area of the world

**Comment by OreCruncher** [comment]
From the log:

```
java.lang.RuntimeException: Attempted to set villager profession to unregistered profession: -1 null
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:334)
	at net.minecraft.entity.passive.EntityVillager.func_184206_a(EntityVillager.java:457)
	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(EntityDataManager.java:167)
	at net.minecraft.entity.passive.EntityVillager.func_70938_b(EntityVillager.java:423)
	at net.minecraft.entity.passive.EntityVillager.<init>(EntityVillager.java:129)
	at matteroverdrive.entity.EntityVillagerMadScientist.<init>(EntityVillagerMadScientist.java:74)
	at matteroverdrive.world.MadScientistHouse.func_74893_a(MadScientistHouse.java:219)
	at matteroverdrive.world.MadScientistHouse.func_74875_a(MadScientistHouse.java:192)
```
Problem appears to be in Matter Overdrive.

**Comment by KiraLinux** [comment]
I understand
