### ISSUE TITLE
Crash During Game launch

### ISSUE THREAD

**Issue by Andyghandi** [OreCruncher/DynamicSurroundings#390]
DynamicSurroundings-1.12.2-3.4.10.0

Forge 2770

Crash Report:

Time: 2018-11-08 17:38:13 CET
Description: Unexpected error

java.lang.NoClassDefFoundError: org/blockartistry/DynSurround/client/sound/SoundEngine
    at net.minecraft.client.audio.SoundManager.getClampedVolume(SoundManager.java)
    at net.minecraft.client.audio.SoundManager.playSound(SoundManager.java:401)
    at net.minecraft.client.audio.SoundHandler.playSound(SoundHandler.java:258)
    at net.minecraft.client.audio.MusicTicker.playMusic(SourceFile:49)
    at net.minecraft.client.audio.MusicTicker.update(SourceFile:43)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1856)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.blockartistry.DynSurround.client.sound.SoundEngine
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
Caused by: java.lang.NullPointerException

The game crashes during launch. From what I can tell, this seems to be caused by Dynamic Surroundings. This started as i Updated a few mods in the twitch launcher, and after adding the mods: Gendustry, metal chests, Not Enough Wands, BeeBetterAtBees and Building gadgets.

**Comment by Andyghandi** [comment]
Ok so the issue is with any of these 5 mods. Let me investigate further

**Comment by Andyghandi** [comment]
By looks of things, I missed a core mod for gendustry. But that didnt show up when launching with all my other 250 mods. It only displayed when I used these 5 mods and dynamic surrounds. However now my complete modpack works as intended!

**Comment by Andyghandi** [comment]
Closing this as there is no crash caused by this mod.

**Comment by OreCruncher** [comment]
Cool!  Thanks for lettting me know.
