### ISSUE TITLE
Server Crash after sleeping

### ISSUE THREAD

**Issue by Freebi85** [OreCruncher/DynamicSurroundings#397]
*Mod Version:*
DynamicSurroundings-1.12.2-3.4.10.0.jar

*Forge Version:*
1.12.2 - 14.23.5.2772

*Link to crash log (if applicable):*
[20:57:29] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:518) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: org/blockartistry/DynSurround/server/PlayerSleepHandler
at net.minecraft.world.WorldServer.func_73051_P(WorldServer.java) ~[oo.class:?]
at net.minecraft.world.WorldServer.func_73053_d(WorldServer.java:292) ~[oo.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:196) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
... 4 more
Caused by: java.lang.ClassNotFoundException: org.blockartistry.DynSurround.server.PlayerSleepHandler
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
at net.minecraft.world.WorldServer.func_73051_P(WorldServer.java) ~[oo.class:?]
at net.minecraft.world.WorldServer.func_73053_d(WorldServer.java:292) ~[oo.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:196) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
... 4 more
Caused by: java.lang.NullPointerException

[20:57:29] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server

**Comment by OreCruncher** [comment]
What modpack are you using?  Also try with v3.4.10.2 (latest release version).  Make sure you remove the older coremod jar from your **instance/mods/1.12.2** folder else the client will crash at startup.

BTW, I can't duplicate the problem.  Figures don't it? :)

**Comment by OreCruncher** [comment]
@Freebi85 Any further update?

**Comment by Freebi85** [comment]
Seems to be solved with latest version. Thanks =)
