### ISSUE TITLE
NPE in blockstate registry

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundings#409]
@TheRealDadbeard
Same crashing here https://paste.dimdev.org/ibogisimuv.mccrash

```
java.lang.NullPointerException
    at org.orecruncher.dsurround.registry.blockstate.BlockStateRegistry.get(BlockStateRegistry.java:110)
    at org.orecruncher.dsurround.client.handlers.scanners.RandomBlockEffectScanner.interestingBlock(RandomBlockEffectScanner.java:75)
    at org.orecruncher.dsurround.lib.scanner.Scanner.update(Scanner.java:150)
    at org.orecruncher.dsurround.client.handlers.AreaBlockEffectsHandler.process(AreaBlockEffectsHandler.java:58)
    at org.orecruncher.dsurround.client.handlers.EffectManager.onTick(EffectManager.java:171)
    at org.orecruncher.dsurround.client.handlers.EffectManager.clientTick(EffectManager.java:181)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_682_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1707)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3941)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by OreCruncher** [comment]
Digging in to this a bit it appears that an IBlockState was not detected during mod initialization - which is down right strange.  I will add some patching code and some diagnostics.  If you still have the world handy and have an update DS JAR installed I would like to get your client log.

**Comment by OreCruncher** [comment]
Version v3.5.0.1 BETA pushed to CurseForge.

**Comment by TheRealDadbeard** [comment]
Not crashing anymore thx. What is this notification on the right side what sounds are playing? Could not find anything how to disable it.
