### ISSUE TITLE
[1.12.2] Crash when entering a world

### ISSUE THREAD

**Issue by TheSnowyChickens** [OreCruncher/DynamicSurroundings#434]
*Mod Version:*
DynamicSurroundings-1.12.2-3.5.4.1BETA
OreLib-1.12.2-3.5.1.3BETA
MC 1.12.2

*Forge Version:*
Forge 2805

*Link to crash log (if applicable):*
https://paste.dimdev.org/enizevalik.mccrash

*Description:*
I disabled a lot of Quark stuff and then I restarted my MC and want to enter the world. :/

**Comment by OreCruncher** [comment]
Did you disable any blocks that would be present in your world?

**Comment by TheSnowyChickens** [comment]
Yes, but I don't placed them into my world.

**Comment by agentwolf88** [comment]
Same here.

Cant connect to my exist world.

**Comment by O13SC3N3** [comment]
I don't know if this is related but ill post it here. (Hi OreCruncher long time, awesome to see this mod flourish!)

Updated to DynamicSurroundings-1.12.2-3.5.4.1BETA.jar, Reverting back to see if it still exist.

> `[20:05:05] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.sound.SoundSetupEvent@3caf37be:
java.lang.NoClassDefFoundError: Could not initialize class org.orecruncher.dsurround.client.sound.SoundEngine
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_383_SoundEngine_configureSound_SoundSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.client.audio.SoundManager.<init>(SoundManager.java:79) [chm.class:?]
	at net.minecraft.client.audio.SoundHandler.<init>(SoundHandler.java:63) [cho.class:?]
	at net.minecraft.client.Minecraft.displayInitErrorScreen(Minecraft.java:4002) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3933) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[20:05:05] [main/ERROR] [FML]: Index: 1 Listeners:
[20:05:05] [main/ERROR] [FML]: 0: LOWEST
[20:05:05] [main/ERROR] [FML]: 1: ASM: class org.orecruncher.dsurround.client.sound.SoundEngine configureSound(Lnet/minecraftforge/client/event/sound/SoundSetupEvent;)V
[20:05:05] [main/ERROR] [minecraft/Minecraft]: An uncaught exception occured while displaying the init error screen, making normal report instead
java.lang.NoClassDefFoundError: Could not initialize class org.orecruncher.dsurround.client.sound.SoundEngine
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_383_SoundEngine_configureSound_SoundSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.client.audio.SoundManager.<init>(SoundManager.java:79) ~[chm.class:?]
	at net.minecraft.client.audio.SoundHandler.<init>(SoundHandler.java:63) ~[cho.class:?]
	at net.minecraft.client.Minecraft.displayInitErrorScreen(Minecraft.java:4002) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3933) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[20:05:05] [main/FATAL] [VanillaFix]: Minecraft ran into a problem! Report saved to: C:\Users\O13SC3N3\Desktop\MultiMC\instances\A0.1.6a (ReWork)\.minecraft\crash-reports\crash-2019-01-04_20.05.05-client.txt`

**Comment by OreCruncher** [comment]
@O13SC3N3 Howdy!  Did you have a dsurround.cfg from a previous version, like 3.4.x or earlier?

**Comment by OreCruncher** [comment]
@agentwolf88 Did you disable Quark blocks like @TheSnowyChickens, or was this a simple drop in a new JAR and start up a world?

**Comment by O13SC3N3** [comment]
@OreCruncher Removed the Config from previous version. Forge 2768, just Single Player

**Comment by OreCruncher** [comment]
OK.  Can you update to Forge 2779+?  Reason is that I discovered a piece of code that is dependent on that version and I don't have any dependency enforcement. :\

**Comment by O13SC3N3** [comment]
> OK. Can you update to Forge 2779+? Reason is that I discovered a piece of code that is dependent on that version and I don't have any dependency enforcement. :\

Ill try it m8. Been a few years been working/scripting my next modpack. Hit a wall with Unidict, I like it but removing recipes is such a pain. I thought about 2779, just wasnt ready to break more mods/configs hehe. 

Ill set up a 2779 environment for my pack, and see how it goes. Thanks man!

**Comment by OreCruncher** [comment]
@TheSnowyChickens Using MultiMC I created a pack based on the mods listed in your crash log.  The config files are at defaults.  I was not able to repro the problem.  Can you zip up your config directory and paste a link?  I want to drop into my instance to see if I can replicate based on what you disabled.

**Comment by TheSnowyChickens** [comment]
Yes I can do this via Curse / Twitch Launcher function. @OreCruncher 
But I still worked on the configs, so its maybe not the state from the crash. (but very similar)

[Pixl Pack-1.0.zip](https://github.com/OreCruncher/DynamicSurroundings/files/2729747/Pixl.Pack-1.0.zip)

**Comment by OreCruncher** [comment]
So far I am still not able to repro using the configs/scripts in the ZIP and with MultiMC. *grumbles*  If you can reliably repro the problem would you mind testing out a "fix" based on what I think may be going on?  It would require updating OreLib as well (latest posted on CurseForge).

**Comment by OreCruncher** [comment]
[I made a JAR](https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.5.4.2TEST).  You will need the latest OreLib from CurseForge, and Forge has to be 2779+.

**Comment by TheSnowyChickens** [comment]
I updated today your lib to the newest version and yesterday forge to 2806.

**Comment by OreCruncher** [comment]
OK - you should be able to drop the test JAR in.  Make sure you disable the previous version (rename it, delete it, etc.)

**Comment by TheSnowyChickens** [comment]
One moment, my English is not the best: You want the I enter my old corrupted World with the test version, right?

**Comment by OreCruncher** [comment]
Correct.

**Comment by TheSnowyChickens** [comment]
Then we have a problem: This corrupted world was a new void world with nothing in it, so I deleted them after the crash.

So please try it with @O13SC3N3  xD

**Comment by OreCruncher** [comment]
@TheSnowyChickens No worries.  Been there myself. :)

**Comment by OreCruncher** [comment]
@agentwolf88 tried out the test JAR and it addressed the issue.  From the client log provided there were 151,977 block states when Minecraft finished loading.  However, when DS detected the missing data on a block state and reconfigured there were 144,699 blockstates.  This means that 7278 blockstates disappeared *after* block registration was completed.  Go figure.  In a nutshell what I thought was happening is happening, and my changes will address the problem.  I will be pushing an update in the next day or so with the fix.

**Comment by agentwolf88** [comment]
thx for info. keep up the good work.

**Comment by TheSnowyChickens** [comment]
Ty

**Comment by OreCruncher** [comment]
Pushed v3.5.4.2 with a fix.

**Comment by TheSnowyChickens** [comment]
Ty²
