### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by ExitCore** [OreCruncher/DynamicSurroundings#489]
Minecraft: v1.12.2
Mod:  v3.5.4.3
Forge: v14.23.5.2837 + v14.23.5.2838

Description: Crashing on startup, all mods work except your mod errors out.
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/3499918/latest.log)

edit: I hope this helps.
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.resources.I18n.format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

**Comment by OreCruncher** [comment]
Have you tried an older version of Forge?  The mod is built against 2768, and I am trying to determine if this is a compatibility issue with newer Forge versions.

**Comment by ExitCore** [comment]
I have tried switching versions of forge to all kind but there was no luck. Also my little sister had the same problem. Since it been at least 2 months ago I've  never installed it again, intil 2 weeks ago and still having the same problem.

**Comment by OreCruncher** [comment]
This pack online somewhere, or something you threw together?  The I18n class it is complaining about is actual Minecraft code.  Usually when something strange like this happens its due to some strange compatibility with another mod that modifies code.

**Comment by DrawingMelon** [comment]
I have the same issue

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/13/19 4:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Surroundings (dsurround)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.resources.I18n.format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
	at org.orecruncher.lib.Localization$ClientImpl.format(Localization.java:58)
	at org.orecruncher.lib.Localization.format(Localization.java:105)
	at org.orecruncher.dsurround.proxy.ProxyClient.postInit(ProxyClient.java:146)
	at org.orecruncher.dsurround.ModBase.postInit(ModBase.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 656754128 bytes (626 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version                  | Source                                         | Signature                                |
	|:------ |:--------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft                   | 1.12.2                   | minecraft.jar                                  | None                                     |
	| UCHIJ  | mcp                         | 9.42                     | minecraft.jar                                  | None                                     |
	| UCHIJ  | FML                         | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                       | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | dsurroundcore               | 3.5.5.0                  | minecraft.jar                                  | None                                     |
	| UCHIJ  | alcatrazcore                | 1.0.4                    | alcatrazcore-1.0.4.jar                         | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| UCHIJ  | mujmajnkraftsbettersurvival | 1.3.4                    | Better_Survival-1.3.4(1.12.1).jar              | None                                     |
	| UCHIJ  | dynamictrees                | 1.12.2-0.9.5             | DynamicTrees-1.12.2-0.9.5.jar                  | None                                     |
	| UCHIJ  | familiarfauna               | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                | None                                     |
	| UCHIJ  | inventorytweaks             | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJ  | millenaire                  | Millénaire 7.2.1         | millenaire-1.12.2-7.2.1.jar                    | None                                     |
	| UCHIJ  | notreepunching              | 2.0.19                   | notreepunching-2.0.19.jar                      | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| UCHIJ  | realistictorches            | 2.1.1                    | RealisticTorches-1.12.2-2.1.1.jar              | None                                     |
	| UCHIJ  | soundfilters                | 0.11_for_1.12            | SoundFilters-0.11_for_1.12.jar                 | None                                     |
	| UCHIJ  | toughasnails                | 3.1.0.141                | Tough-As-Nails-Mod-1.12.2.jar                  | None                                     |
	| UCHIJ  | orelib                      | 3.5.2.3                  | OreLib-1.12.2-3.5.2.3-deobf.jar                | None                                     |
	| UCHIEE | dsurround                   | 3.5.5.0                  | DynamicSurroundings-1.12.2-3.5.5.0.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHI   | dshuds                      | 3.5.4.0                  | DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
  org.orecruncher.dsurround.asm.Transformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14523 Compatibility Profile Context 24.20.12019.1010' Renderer: 'AMD Radeon R7 240'

**Comment by OreCruncher** [comment]
Need the client log please. :)  The above is the crash log.  It's in the log directory and it is called "latest.txt".

**Comment by DrawingMelon** [comment]
https://ufile.io/zmyyxls9
I can't copy paste it, it's says it's too long

**Comment by OreCruncher** [comment]
This the right log?  I don't see anything related to dynamic surroundings in the log.

**Comment by DrawingMelon** [comment]
is this one better ?
https://ufile.io/820iob8y

**Comment by OreCruncher** [comment]
Yep.  Much better.  Is this pack something you put together or is it available some where?

**Comment by DrawingMelon** [comment]
I installed it and it works now, thank you !!

**Comment by OreCruncher** [comment]
Good!  Glad to hear it.  Let me know if you run into any further strangeness. :)

@ExitCore, you also have the deobf version installed.  Change it to the regular release version.
