### ISSUE TITLE
DS incompatibility with Advanced Rocketry + load stall

### ISSUE THREAD

**Issue by Gamertech** [OreCruncher/DynamicSurroundings#514]
**Mod Version:**
1.12.2-3.6.0.1

**Forge Version:**
14.23.5.2847

**Link to client log:**
https://pastebin.com/HW2YwE3r

**Link to crash log:**
https://pastebin.com/HBB0vxVm

**Description:**
If a mod is missing a dependancy (in this case FTB Utilities) and locks onto the Forge missing dependancy screen, DS will error out and crash the pack.

**Comment by OreCruncher** [comment]
I think the whole startup process is hosed up.  Despite the fact the client will not start, something somewhere insists on playing music which triggers the DS sound engine code, which in turn causes it to use a reflection support class from OreLib, which cannot be found.

Up further in the log is this output:
```
[13:29:45] [main/ERROR]: A critical problem occurred registering the ASM transformer class
java.lang.ClassNotFoundException:
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
    at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:46) [forge-1.12.2-14.23.5.2847.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    ... 6 more
```
The times I have seen this all bets are off.  Is this trace present after you get the pack cleaned up?

**Comment by Gamertech** [comment]
Yea, if the version mismatch is fixed, the pack loads perfectly with the same version of DS, but the same exception is showing in the logs.

Ah found it, The exception's coming from Advanced Rocketry.

**Comment by OreCruncher** [comment]
I found that by changing the priority of the render event handler I can work around the issue.

**Comment by OreCruncher** [comment]
Found a work around to avoid the crash.

**Comment by OreCruncher** [comment]
Pushed v3.6.0.2 with fix.

**Comment by Gamertech** [comment]
Thanks mate
