### ISSUE TITLE
crash with ichun

### ISSUE THREAD

**Issue by V-Boy** [OreCruncher/DynamicSurroundings#542]
**Mod Version:**3.6.0.2  

**Forge Version:**14.23.5.2847

**Link to client log:**

client log contains my IP 

**Link to crash log:**
https://paste.dimdev.org/tanixevari.mccrash

**Description:**

whenever i click the background of JEI, it crashes to the menu repeatidly, might have to do something with iChun according to vanillafix. i have had this mod for a while, and the crashes with ichun would occasionally happen but now it keeps happening.

**Comment by OreCruncher** [comment]
It looks fishy.  Can you post a link to your client log that contains the error?  I need to see the sequence of events.

**Comment by V-Boy** [comment]
https://hastebin.com/uhikozukuh.md

is this good enough?

**Comment by OreCruncher** [comment]
Yep.  Looks like an entity is being spawned client side during a render event.  That is not right.

```
java.lang.NullPointerException
    at org.orecruncher.dsurround.client.handlers.EnvironStateHandler$EnvironState.isPlayer(EnvironStateHandler.java:155)
    at org.orecruncher.dsurround.client.handlers.SoundEffectHandler.playerJoinWorldEvent(SoundEffectHandler.java:192)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3246_SoundEffectHandler_playerJoinWorldEvent_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.spawnEntity(World.java:1209)
    at net.minecraft.client.multiplayer.WorldClient.spawnEntity(WorldClient.java:259)
    at me.ichun.mods.ichunutil.client.core.EntityTrackerHandler.onRenderTickStart(EntityTrackerHandler.java:58)
    at me.ichun.mods.ichunutil.client.core.event.EventHandlerClient.onRenderTick(EventHandlerClient.java:160)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1705_EventHandlerClient_onRenderTick_RenderTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
```

I can see if I can patch around it.

**Comment by OreCruncher** [comment]
Pushed 3.6.1.0 to CurseForge.
