### ISSUE TITLE
Mod Causes Game To Crash During "Finishing Up" stage of loading

### ISSUE THREAD

**Issue by Robonics** [OreCruncher/DynamicSurroundings#550]
**Mod Version: DynamicSurroundings-1.12.2-3.6.0.2.jar**

**Forge Version: Forge 1.12.2-14.23.5.2847**

**[Crash Log](https://pastebin.com/fKriGcjx)**

**[latest.log](https://drive.google.com/file/d/1QgVsfSQxsGeqANbsTHha8PW7t5wGCHz-/view?usp=sharing)** (Had to use Drive due to file size)

**[debug.log](https://drive.google.com/file/d/1E8VyqiWRqspyEzKTy2B4KvHF6GQkhVyE/view?usp=sharing)**

The game boots up fine until it reaches the *Finishing Up* stage of loading, it gets to Dynamic Surroundings and crashes withing seconds. Removing Dynamic Surroundings seems to fix the issue. 

[This](https://imgur.com/a/epgAtkb) is a image of my mods folder.

Dynamic surroundings worked fine in my last pack which had most of the same client mods, so I have no clue what is causing this issue.

**Comment by OreCruncher** [comment]
Can you provide the client side log?

**Comment by Robonics** [comment]
Where would I find that? All I see is `latest.log` which is what I posted above

**Comment by OreCruncher** [comment]
What is linked above is the crash log.

**Comment by Robonics** [comment]
Sorry, seems I'm just an idiot. All of the logs I could find are there now. Sorry in advance if it still isn't all you need.

**Comment by OreCruncher** [comment]
Oooo ... looks like things are not happy.  Don't think this is DS specifically.  Here are exceptions from the log:

```
[14:31:12] [Client thread/INFO] [STDERR]: [futurepack.extensions.albedo.AlbedoMain:init:46]: java.lang.NoSuchMethodException: elucent.albedo.event.GatherLightsEvent.add()
[14:31:12] [Client thread/INFO] [STDERR]: [futurepack.extensions.albedo.AlbedoMain:init:46]: 	at java.lang.Class.getMethod(Class.java:1786)
[14:31:12] [Client thread/INFO] [STDERR]: [futurepack.extensions.albedo.AlbedoMain:init:46]: 	at futurepack.extensions.albedo.AlbedoMain.init(AlbedoMain.java:32)
[14:31:12] [Client thread/INFO] [STDERR]: [futurepack.extensions.albedo.AlbedoMain:init:46]: 	at futurepack.common.FPMain.preInit(FPMain.java:201)
```

```
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: java.lang.reflect.InvocationTargetException
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at techguns.client.models.guns.ModelBaseBakedGrenadeLauncher.render(ModelBaseBakedGrenadeLauncher.java:35)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at techguns.client.render.item.RenderGunBase.renderItem(RenderGunBase.java:310)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at techguns.client.render.ItemRenderHack.renderItem(ItemRenderHack.java:73)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:517)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:356)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:29:24] [Client thread/INFO] [STDERR]: [techguns.client.models.guns.ModelBaseBakedGrenadeLauncher:render:48]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:29:24] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 28
[15:29:24] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraftforge.client.model.pipeline.LightUtil.pack(LightUtil.java:245)
[15:29:24] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.func_178209_a(UnpackedBakedQuad.java:53)
[15:29:24] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.client.renderer.RenderItem.func_191969_a(RenderItem.java:331)
[15:29:24] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:372)
[15:29:24] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:171)
[15:29:24] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)
[15:29:24] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 29 more
```

```
[15:29:43] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1486) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:303) ~[buk.class:?]
	at net.minecraft.client.renderer.RenderItem.func_181565_a(RenderItem.java:703) ~[bzw.class:?]
```

Not sure if these are real problems but I figured I would point out:

```
[14:34:14] [Client thread/ERROR] [net.optifine.shaders.SMCLog]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_entities (gbuffers_textured), at: pre-useProgram
[14:34:14] [Client thread/ERROR] [net.optifine.shaders.SMCLog]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_entities (gbuffers_textured), at: pre-useProgram
```

```
[14:35:26] [Thread-29/ERROR] [soundfilters]: Caught AL error in 'loadSourceFilter attempt 1'! Error is 40961
[14:35:26] [Thread-29/ERROR] [soundfilters]: Caught AL error in 'load3SourceFilters attempt 1'! Error is 40963
```

Dynamic Surroundings is not the lists.  Not sure how the presence of DS intersects with this problem.  However, the last exception generated in the log prior to the crash is related to "TechGuns".  Have you tried removing that mod to see if the behavior changes?

**Comment by Robonics** [comment]
I'll try removing TechGuns. Also I'm not sure about the OpenGL errors. I have my shaders off for performance reasons, but I'll look into that.

**Comment by Robonics** [comment]
I reinstalled Optifine, removed TechGuns and added Dynamic Surroundings Back. Game still crashed, these are the new error logs:
[latest](https://drive.google.com/file/d/1bCEsFIXyBrZU-479_VELHMQsfjEpLLNQ/view?usp=sharing)
[debug](https://drive.google.com/file/d/1dPQi1kK5p0u0zkgZ-zWKw0j3yzcSDByp/view?usp=sharing)

**Comment by OreCruncher** [comment]
Has this ever worked in this pack?  Here is the relevant callstack:

```
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ExceptionInInitializerError
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.orecruncher.dsurround.event.WorldEventDetector.func_184376_a(WorldEventDetector.java:64)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.func_184138_a(World.java:432)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.func_175700_a(World.java:1930)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.func_175690_a(World.java:2463)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:624)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.func_180501_a(World.java:343)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.client.multiplayer.WorldClient.func_180501_a(WorldClient.java:655)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.func_175656_a(World.java:425)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.crafting.FPAirBrushRecipes.lambda$null$0(FPAirBrushRecipes.java:82)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.crafting.FPAirBrushRecipes$$Lambda$816/2042895473.accept(Unknown Source)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.crafting.FPAirBrushRecipes.lambda$run$1(FPAirBrushRecipes.java:80)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.crafting.FPAirBrushRecipes$$Lambda$815/150317451.accept(Unknown Source)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Iterable.forEach(Iterable.java:75)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at futurepack.common.crafting.FPAirBrushRecipes.run(FPAirBrushRecipes.java:64)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.NullPointerException
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.orecruncher.dsurround.client.handlers.EnvironStateHandler$EnvironStateData.<init>(EnvironStateHandler.java:72)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.orecruncher.dsurround.client.handlers.EnvironStateHandler$EnvironState.<clinit>(EnvironStateHandler.java:99)
[11:23:46] [Airbush Recipe Scanner/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 16 more
```

It looks like the futurepack registration process is calling setblockstate (that is the func_175656_a) which in turn will notify all listeners of a block change.  DS does have a registration to listen for block updates client side (at org.orecruncher.dsurround.event.WorldEventDetector.func_184376_a) that gets triggered.  The problem here is that the client is not loaded thus DS crashes unexpectedly.  If for whatever reason FP needs to set blockstate they need to have it so it does not notify.

**Comment by Robonics** [comment]
So I need to inform FuturePack’s author then? Thanks for the help, not very familiar with Minecraft Modding or for that matter Java but I think I have the concept.

**Comment by OreCruncher** [comment]
Yes, I would notify them.  I will leave open - when I get a chance I will look to see if I can add some defensive code.

**Comment by Khris777** [comment]
I came here because I have the same issue and found the issue over at Futurepack from which they redirect back here, saying it's now your issue again.

https://github.com/mcenderdragon/Futurepack-API/issues/633

**Comment by OreCruncher** [comment]
Can you try out this build I have here: https://github.com/OreCruncher/DynamicSurroundings/releases/tag/3.6.1.0  I updated Mixin to the latest.

**Comment by Khris777** [comment]
New version leads to an immediate crash during initialisation:

```
[10:23:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:23:15] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader.fail(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader.access$100(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$LazyIterator.access$700(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$LazyIterator$2.run(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.security.AccessController.doPrivileged(Native Method)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.util.ServiceLoader$1.next(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:23:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.checkCerts(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.preDefineClass(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.getConstructor0(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 27 more
[10:23:15] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[10:23:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[10:23:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[10:23:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[10:23:15] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main"
``

**Comment by OreCruncher** [comment]
That looks to be something totally different.  Can you link the debug.log?  Were any other mods updated between the time of initial report and when you tried out the new version?

**Comment by Khris777** [comment]
I'm working on a modpack, so things change a lot. However this error is only thrown when I change the version of Dynamic Surroundings and nothing else.

Here's the full debug.log: https://pastebin.com/bBm4VGeL

**Comment by OreCruncher** [comment]
Arcane Archives is using 0.2.0.16 Mixin 0.7.11.  Update to 0.2.0.17 - it uses Mixin 0.8.1.

**Comment by Khris777** [comment]
Thanks.

But I guess I'll need to wait now for other mods to get updated because of [mixin version incompatibilities](https://github.com/AranaiRa/ArcaneArchives/issues/91).

**Comment by OreCruncher** [comment]
Yeah.  The latest STABLE version of mixin is 0.8.  0.8.1 (which is included in Arcane Archives) is bleeding edge development build.  If they don't need 0.8.1 they should probably stick with 0.8.

**Comment by OreCruncher** [comment]
Pushed 3.6.1.0 to CurseForge.  This updates Mixin to the latest stable (0.8).  Since this resolve the issue for Dynamic Surroundings I am going to close.  However, as things progress feel free to keep updating this issue as needed.
