### ISSUE TITLE
Unknown ConcurrentModificationException (not sure if related)

### ISSUE THREAD

**Issue by LiskoSlayer63** [OreCruncher/DynamicSurroundings#561]
**Mod Version:** 3.6.0.2
**OreLib Version:** 3.6.0.1
**Forge Version:** 14.23.5.2847 
**Link to client log:** [client log](https://download.liznet.fi/files/client_log.txt)
**Link to crash log:** [crash log](https://paste.dimdev.org/inavuloneg.mccrash)

**Description:**
The mod have been existed in my modpack for a while, but I just did a full update to all mods. This particular crash related to a SoundManager did NOT happen before the update, but there was another unknown crash related to entity updates (NullReferenceException). That crash disappeared after the update, though. (or it did not, because the world is new)

I have a couple of versions of the pack, which changes how heavy the client is. This crash happens only with the heaviest version (Ultra) which also have AmbientSounds and SoundFilters installed. They might be related OR cause it, I can't tell what mod actually causes this.

**Reasons why I think the crash is caused by your mod:**
The Medium version had reported to never crash by users, and that version does not have these three mods installed. As far as I know, the High version too have not crashed and it have everything else but Dynamic Surroundings installed. That's why I'm reporting this crash here.

**Is the modpack you are using available online somewhere?** 
Yes and no, the packs are integrated with a custom launcher.

**Comment by OreCruncher** [comment]
Some other errors reported in the log:

This one will show up sporadically after the initial flurry of reports:
```
[07:26:48] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:26:48] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tryAmbientSounds(SceneEnhancer.java:431)
[07:26:48] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tickClientThreaded(SceneEnhancer.java:241)
[07:26:48] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.run(SceneEnhancer.java:177)
[07:26:48] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at java.lang.Thread.run(Unknown Source)
[07:27:09] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:27:09] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tryAmbientSounds(SceneEnhancer.java:431)
[07:27:09] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tickClientThreaded(SceneEnhancer.java:241)
[07:27:09] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.run(SceneEnhancer.java:177)
[07:27:09] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at java.lang.Thread.run(Unknown Source)
[07:27:37] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:27:37] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tryAmbientSounds(SceneEnhancer.java:431)
[07:27:37] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tickClientThreaded(SceneEnhancer.java:241)
[07:27:37] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.run(SceneEnhancer.java:177)
[07:27:37] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at java.lang.Thread.run(Unknown Source)
[07:28:29] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:28:29] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tryAmbientSounds(SceneEnhancer.java:431)
[07:28:29] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tickClientThreaded(SceneEnhancer.java:241)
[07:28:29] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.run(SceneEnhancer.java:177)
[07:28:29] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at java.lang.Thread.run(Unknown Source)
[07:29:28] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:30:23] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:30:53] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:31:21] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:31:49] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:34:19] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:36:11] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:36:46] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:37:15] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:37:50] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:38:15] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:38:44] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:39:14] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:39:47] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
[07:40:16] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.NullPointerException
```

This is considered fatal and occurs before the DS related one:

```
[08:01:02] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
	at net.minecraft.world.World.updateEntities(World.java:1825) ~[amu.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847) ~[bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?
```

Not sure if this is a result of the failed load:
```
[08:07:09] [Netty Client IO #4/INFO]: Rejecting connection SERVER: Recurrent Complex: Failed mod's custom NetworkCheckHandler FMLMod:reccomplex{1.4.8.2}
```

And finally the one that caused you to open the issue here:
```
java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:401)
    at net.minecraft.client.audio.SoundManager.updateAllSounds(SoundManager.java:252)
    at net.minecraft.client.audio.SoundHandler.update(SoundHandler.java:293)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1858)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

This exception is related to the fact that a non-client thread was interacting with sound manager which is a big no-no.  DS interacts heavily with the sound manager doing its sound management, but all that occurs on the client thread.  So if another thread is indeed accessing the list at the same time you can get this exception.

**Comment by LiskoSlayer63** [comment]
"Unknown" NullPointerException is very old crash, we have suffered from it about 1-2 years now, because nobody knows how to fix it or what causes it. Back then when it first occured Weather was not installed. 

Weather mod NullPointerException happens because of the Menu Mobs mod, not sure why though. It spams that when on a main menu, nothing dangerous.

What do you recommend to do at my situation? I have now two "unknown" crashes, one related to sounds and one related to entities.

**Comment by OreCruncher** [comment]
Try this: https://dynamicsurroundings.readthedocs.io/en/master/debugging.html  It may give more details as to what is going on.

**Comment by OreCruncher** [comment]
@LiskoSlayer63 Its been a bit and I was wondering if you tried out enabling the diagnostic feature in DS.

**Comment by LiskoSlayer63** [comment]
@OreCruncher I actually forgot this whole problem, it seems to have disappeared now. I had LiteLoader installed for a long time, but then updated the modpack to use Forge only. That fixed _many_ problems and crashes, maybe this one too. I will enable that diagnostic feature and open a new issue (or revive this) if the problem appears again.
