### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [OreCruncher/DynamicSurroundings#570]
**Mod Version:** 3.6.1.0

**Forge Version:** 14.23.5.2854

**Link to client log:** https://hastebin.com/viniwehuwu.md

**Link to crash log:** /

**Description:**
Seems like another Mixin problem, might not caused by DS itself, but before OreLib and DS were added, everything works just fine.

The mods below in the pack also uses Mixin, more information were included in the log.

- JustEnoughIDs 1.0.3-55
- levelup2 1.4.2
- performant 1.10
- Surge 2.0.79
- TimeCore 1.0.1.1
- VanillaFix 1.0.10-150
- phosphor 0.2.7

**Comment by OreCruncher** [comment]
The linked log is empty.  However, I suspect it is related to Mixin.  Make sure that all your mods are up to date, and if they use mixin they use version 0.8.  (VanillaFix and Phosphor should be fine - not sure of the others.)

**Comment by ChromaPIE** [comment]
It is caused by Performant, already post an issue to their repository, thanks.

**Comment by ChromaPIE** [comment]
Something weird happened. First, DS 3.6.1.0 is sure to be incompatible with Performant 1.10, but when I deleted **ORECRUNC.RSA** and **ORECRUNC.SF** in the **META-INF** folder of DynamicSurroundings-1.12.2-3.6.1.0, the game successfully launched with Performant. Please check if something went wrong with these two files or it's Performant's problem.

**Comment by bolte-io** [comment]
I have this same issue, it clashes on security classes...
`java.lang.SecurityException: class "org.spongepowered.asm.launch.platform.CommandLineOptions"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.preDefineClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_261]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_261]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_261]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_261]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_261]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_261]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_261]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at org.spongepowered.asm.launch.MixinTweaker.acceptOptions(MixinTweaker.java:55) ~[DynamicSurroundings-1.12.2-3.6.1.0.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

But, if you change the load order and allow Performant to load first, by say, putting a z before the name of the file, it fixes this and allows Minecraft to load, but causes some other errors with your dependency, OreLib...

Warnings: 
`[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$profiles::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$commands::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$commands$calc::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$commands$ds::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$speechbubbles::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$player::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$sound::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$effects::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$biomes::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$aurora::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$general::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$fog::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$rain::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$logging::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$asm::PATH]`

And in debug log:
`[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$profiles::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$commands::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$commands$calc::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$commands$ds::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$speechbubbles::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$player::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$sound::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$effects::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$biomes::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$aurora::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$general::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$fog::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$rain::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$logging::PATH]
[23:24:35] [Client thread/WARN] [orelib]: Unable to locate field [org.orecruncher.dsurround.ModOptions$asm::PATH]`

It would be amazing if you could work around this incompatibility.

**Comment by bolte-io** [comment]
To simplify, this can be fixed/workaround by changing the filename/order that DS loads in.
But, obviously to include it in packs that generate manifests, it needs to be loaded last/after performant.

**Comment by bolte-io** [comment]
Ok so I found a fix, someone threw up a mod to resolve the mixin related crash on startup:
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

My logs of the issue for your information:
https://paste.ee/p/aVZZN

**Comment by bolte-io** [comment]
PS: I have tested it, and it allows Performant and DS to load rather than crash.

**Comment by OreCruncher** [comment]
Posted 3.6.2.0 to CurseForge as BETA.  MixinBoostrap will also need to be installed.
