### ISSUE TITLE
IC2Classic issues (crash + unstoppable sounds, again)

### ISSUE THREAD

**Issue by DBotThePony** [OreCruncher/DynamicSurroundings#575]
**Mod Version:** 3.8.1.0
**Forge Version:** Build 2854
**Description:**
https://github.com/TinyModularThings/IC2Classic/issues/410

From issue above, to reproduce unstoppable sounds:
1. Install IC2C + DynamicSurroudings + OreLib
2. Start a world/join a (dedicated) server
3. Put a machine which make looped noise sound (e.g. geothermal generator) and activate it, deploy charged chainsaw in hand, etc.
4. /stop, /kick or sometimes simple disconnect do reproduce the issue
5. Minecraft client continue to play loop sound, it can not be stopped by using "Stop IC2 sounds" in sound settings (idk why IC2C even put a dedicated menu for itself in vanilla sound settings menu)

To reproduce the crash:
1. Install IC2C + DynamicSurroudings + OreLib
2. Start a world/join a (dedicated) server
3. Shift + F8
4. Try to use IC2C wrench on IC2C machine
5.
```
java.lang.NullPointerException
    at paulscode.sound.SoundSystem.quickPlay(SoundSystem.java:857)
    at ic2.core.audio.AudioManagerClient.playOnce(AudioManagerClient.java:208)
    at ic2.core.item.tool.ItemToolWrench.onItemUseFirst(ItemToolWrench.java:136)
    at ic2.core.item.tool.electric.ItemElectricToolWrench.onItemUseFirst(ItemElectricToolWrench.java:125)
    at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:200)
    at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock(PlayerControllerMP.java:409)
    at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1579)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2254)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
```

*Keep in mind that IC2C was the first mod to me to experience problems with DynamicSurroudings so far, and i suspect IC2C contain very old code which cause issues with replacements of paulscode by other mods*

**Comment by OreCruncher** [comment]
@DBotThePony This only happens on a dedicate server?  I am running single player and I am not seeing the issue.

**Comment by DBotThePony** [comment]
As i remember it were reproduce-able in singleplayer
