### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by MrRedstoneA1** [OreCruncher/DynamicSurroundings#614]
**Mod Version:**

Version 3.6.1.0

**Forge Version:**

Version 14.23.5.2854

**Link to client log:**

file:///D:/Program%20Files/MultiMC/mmc-stable-win32/MultiMC/instances/1.12.2/.minecraft/logs/latest.log

**Link to crash log:**

file:///D:/Program%20Files/MultiMC/mmc-stable-win32/MultiMC/instances/1.12.2/.minecraft/crash-reports/crash-2020-12-03_05.18.39-client.txt

**Description:**

I've been using Dynamic Surroundings for months and it has never caused a crash before. I was flying with a plane from Immersive Vehicles, banked to the left and as the chunks loaded, it crashed. Apparently the cause was java.lang.NegativeArraySizeException
    at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:30)
    at org.orecruncher.lib.chunk.PassThroughChunkCache.update(PassThroughChunkCache.java:83)
which a person who knows more about modding pinpointed for me. This lead me here. I know nothing about crash logs so I have no clue what actually caused the crash. The crash just happened unexpectedly. It has not happened before while playing. As far as I know, the crash only happened this one time while flying. I do not know if it happens while running as well.

* Did you just add the mod to a pack?
No.
* Did it just start crashing, or has it always crashed?
First time.
* Did you update any other mods in your pack and it started crashing?  This includes Forge.
No.
* If updating multiple mods did you update one by one or all at once?  To help narrow the problem down adding one by one is helpful.
No updates recently.
* Is the modpack you are using available online somewhere?  If the crash is due to mod interaction having the pack available makes things much easier.  It is much harder to work these types of issues with a private kitchen sink pack containing 250 mods.
No, but I can give a list of mods if needed.

**Comment by OreCruncher** [comment]
Unfortunately the logs aren't attached - looks like the URIs reference files on your system.  You can paste them using pastebin.com and put the link here.  The log file should contain everything I need.

**Comment by MrRedstoneA1** [comment]
Yeah that didn't go as planned. Here's the crash log:
https://pastebin.com/NxwLYfaz
here's the client log:
https://pastebin.com/qg0bk5Mc
I had to cut down the client log, because it was 5 hours long and was too large for pastebin. I cut it to about 10 minutes before the crash happened.

**Comment by OreCruncher** [comment]
Nothing stands out, though it looks like shaders and Rogue Like Dungeons are having some challenges.  Set "Enable Client Chunk Caching" to false in the dsurround.cfg.

**Comment by MrRedstoneA1** [comment]
Alright, thank you.

**Comment by OreCruncher** [comment]
Let me know if the change works.

**Comment by MrRedstoneA1** [comment]
I haven't crashed since and I'm hoping this fixed the crash for good. I'll
let you know if I crash again, but thus far everything's working perfectly.

su 6. jouluk. 2020 klo 6.40 OreCruncher <notifications@github.com>
kirjoitti:
