### ISSUE TITLE
[1.16.4] World Crash with DS v.4.0.3.0 

### ISSUE THREAD

**Issue by andreadx95** [OreCruncher/DynamicSurroundings#636]
**Mod Version:**

DynamicSurroundings-1.16.4-4.0.3.0

**Forge Version:**

1.16.4-forge-35.1.13

**Description:**
Starting a world in single player , make the game crash on load with this log:

**Client log:**
_java.lang.NullPointerException: Starting integrated server
	at org.orecruncher.sndctrl.audio.acoustic.SimpleAcoustic.<init>(SimpleAcoustic.java:49) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.sndctrl.library.Primitives.getArmorToolbarAcoustic(Primitives.java:111) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.mobeffects.library.ItemLibrary.resolveClass(ItemLibrary.java:122) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.mobeffects.library.ItemLibrary.access$400(ItemLibrary.java:47) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.mobeffects.library.ItemLibrary$ItemLibraryService.start(ItemLibrary.java:226) ~[?:1.16.4-4.0.3.0] {re:classloading}
	at org.orecruncher.lib.service.IClientService.reload(IClientService.java:39) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.service.ClientServiceManager$$Lambda$13512/1679782068.accept(Unknown Source) ~[?:?] {}
	at org.orecruncher.lib.service.ClientServiceManager.lambda$performAction$0(ClientServiceManager.java:103) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.service.ClientServiceManager$$Lambda$13468/1502613891.apply(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
	at org.orecruncher.lib.service.ClientServiceManager.performAction(ClientServiceManager.java:106) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.service.ClientServiceManager.reload(ClientServiceManager.java:67) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.service.ClientServiceManager.onStart(ClientServiceManager.java:79) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_1043_ClientServiceManager_onStart_TagsUpdatedEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraft.tags.ITagCollectionSupplier.func_242212_e(ITagCollectionSupplier.java:25) ~[?:?] {re:classloading}
	at net.minecraft.resources.DataPackRegistries.func_240971_i_(DataPackRegistries.java:84) ~[?:?] {re:mixin,re:classloading,xf:fml:placebo:recipemanager}
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1736) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$loadWorld$29(Minecraft.java:1799) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$13456/334453396.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.Minecraft.lambda$deleteWorld$30(Minecraft.java:1829) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$13457/433080443.proceed(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.ConfirmBackupScreen.func_212992_b(SourceFile:40) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.ConfirmBackupScreen$$Lambda$13465/846783432.onPress(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.legacy.structure_gel.SGClientEvents.skipExperimentalBackupScreen(SGClientEvents.java:59) ~[?:1.7.2] {re:classloading,pl:runtimedistcleaner:A}
	at com.legacy.structure_gel.SGClientEvents$$Lambda$4563/792283718.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2970/1125255799.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:291) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:717) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$466/1847825207.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.orecruncher.sndctrl.audio.acoustic.SimpleAcoustic.<init>(SimpleAcoustic.java:49) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.sndctrl.library.Primitives.getArmorToolbarAcoustic(Primitives.java:111) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.mobeffects.library.ItemLibrary.resolveClass(ItemLibrary.java:122) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.mobeffects.library.ItemLibrary.access$400(ItemLibrary.java:47) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.mobeffects.library.ItemLibrary$ItemLibraryService.start(ItemLibrary.java:226) ~[?:1.16.4-4.0.3.0] {re:classloading}
	at org.orecruncher.lib.service.IClientService.reload(IClientService.java:39) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.service.ClientServiceManager$$Lambda$13512/1679782068.accept(Unknown Source) ~[?:?] {}
	at org.orecruncher.lib.service.ClientServiceManager.lambda$performAction$0(ClientServiceManager.java:103) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.service.ClientServiceManager$$Lambda$13468/1502613891.apply(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
	at org.orecruncher.lib.service.ClientServiceManager.performAction(ClientServiceManager.java:106) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.service.ClientServiceManager.reload(ClientServiceManager.java:67) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.service.ClientServiceManager.onStart(ClientServiceManager.java:79) ~[?:1.16.4-4.0.3.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_1043_ClientServiceManager_onStart_TagsUpdatedEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraft.tags.ITagCollectionSupplier.func_242212_e(ITagCollectionSupplier.java:25) ~[?:?] {re:classloading}
	at net.minecraft.resources.DataPackRegistries.func_240971_i_(DataPackRegistries.java:84) ~[?:?] {re:mixin,re:classloading,xf:fml:placebo:recipemanager}
-- Starting integrated server --
Details:
	Level ID: Nuovo mondo (2)
	Level Name: Nuovo mondo
Stacktrace:
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1736) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$loadWorld$29(Minecraft.java:1799) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$13456/334453396.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.Minecraft.lambda$deleteWorld$30(Minecraft.java:1829) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$13457/433080443.proceed(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.ConfirmBackupScreen.func_212992_b(SourceFile:40) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.ConfirmBackupScreen$$Lambda$13465/846783432.onPress(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.legacy.structure_gel.SGClientEvents.skipExperimentalBackupScreen(SGClientEvents.java:59) ~[?:1.7.2] {re:classloading,pl:runtimedistcleaner:A}
	at com.legacy.structure_gel.SGClientEvents$$Lambda$4563/792283718.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2970/1125255799.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:291) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:717) ~[?:?] {re:classloading}

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.WorkingScreen
	Mouse location: Scaled: (293, 70). Absolute: (587.000000, 141.000000)
	Screen size: Scaled: (800, 450). Absolute: (1600, 900). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:821) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$466/1847825207.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}_

**Comment by agentwolf88** [comment]
Same

https://paste.ee/p/Hl6Zu

**Comment by OreCruncher** [comment]
Does this happen all the time, or is it sporadic?

EDIT: Try out this test build.  I made some changes based on some guesses: https://github.com/OreCruncher/DynamicSurroundings2/releases/tag/v4.0.3.1-Testing

**Comment by GnomTocha** [comment]
World generation crash.
Checked v4.0.3.1 Testing. Test v4.0.3.1 is working.
Below there will be crash logs.
[crash-2021-01-06_17.44.16-client.txt](https://github.com/OreCruncher/DynamicSurroundings/files/5776909/crash-2021-01-06_17.44.16-client.txt)
[debug.log](https://github.com/OreCruncher/DynamicSurroundings/files/5776910/debug.log)
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/5776914/latest.log)

**Comment by andreadx95** [comment]
Checked the v4.0.3.1 ,no more crash when loading my world

**Comment by OreCruncher** [comment]
Good.  I will be posting an update later today.  When posted you need to not use the Test version.  The one on CurseForge will have other fixes.

**Comment by GnomTocha** [comment]
OK. Thx

**Comment by andreadx95** [comment]
Great , thanks

**Comment by OreCruncher** [comment]
Pushed 4.0.3.1 to CurseForge.
