### ISSUE TITLE
Crashing 1.16.5

### ISSUE THREAD

**Issue by ghost** [OreCruncher/DynamicSurroundings#677]
```
java.lang.NullPointerException: Rendering overlay
	at net.minecraft.client.shader.ShaderLinkHelper.func_148077_a(SourceFile:21) ~[?:?] {re:classloading}
	at org.orecruncher.lib.shaders.ShaderManager$$Lambda$23388/2105525350.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at org.orecruncher.lib.shaders.ShaderManager.lambda$initShaders$0(ShaderManager.java:178) ~[?:1.16.4-4.0.3.9] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.shaders.ShaderManager$$Lambda$8165/535484738.func_195410_a(Unknown Source) ~[?:?] {}
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:18) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.resources.IResourceManagerReloadListener$$Lambda$8327/1728565728.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$23365/1140785258.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:HookOpenScreen,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:assets/offhandcombat/offhandcombat.mixins.json:RightClickMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercontrols.mixins.json:HookOpenScreen,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:assets/offhandcombat/offhandcombat.mixins.json:RightClickMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.22.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$492/668330752.call(Unknown Source) [forge-1.16.5-36.0.22.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.shader.ShaderLinkHelper.func_148077_a(SourceFile:21) ~[?:?] {re:classloading}
	at org.orecruncher.lib.shaders.ShaderManager$$Lambda$23388/2105525350.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at org.orecruncher.lib.shaders.ShaderManager.lambda$initShaders$0(ShaderManager.java:178) ~[?:1.16.4-4.0.3.9] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.shaders.ShaderManager$$Lambda$8165/535484738.func_195410_a(Unknown Source) ~[?:?] {}
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:18) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.resources.IResourceManagerReloadListener$$Lambda$8327/1728565728.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$23365/1140785258.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
-- Overlay render details --

**Comment by OreCruncher** [comment]
Modpack?  I am using DW20 w/OptiFine and I do not see this issue.

EDIT:  Also, can you attach the complete crash log?
EDIT2:  I will also need to see the debug.log as well.  Looks like something is happening during startup to cause a problem.

**Comment by ghost** [comment]
I seem to not be able to reproduce after trying to run game again, gunna close for now and reopen if it recurrs much sorry

**Comment by OreCruncher** [comment]
No worries. :)
