### ISSUE TITLE
exit code zero with latest 1.12.2 release **catastrophic failure**

### ISSUE THREAD

**Issue by Sulferix** [OreCruncher/DynamicSurroundings#740]
**Mod Version:**

DynamicSurroundings-1.12.2-3.6.1.0

**Forge Version:**
2855

**Link to client log:**
exit code zero.
**Link to crash log:**

exit code zero
**Description:**
the single most annoying possible mod failure is exit code zero. the fact that this mod only has that issue with the last release version(not beta) 1.12.2 file is beyond infuriating. this mod single handedly prevented my from updating my modpack and gave me one of the biggest headaces ive ever had. a crash with NO CRASH LOG and NO LOG OF ANY KIND. yikes. dont go telling me i didnt provide enough information either. thanks to exit code zero, i dont even get any. i will not test this with deleting all 218 of my mods either. not worth the headace. if someone wants to dig in than go ahead, ill attatch my mod list with this unrelated crash log.

https://paste.dimdev.org/otifewifom.mccrash

there needs to at least be a post with that 1.12 release explaining the possibility of this issue or a removal of that version entirely.

**Comment by OreCruncher** [comment]
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Betweenlands (thebetweenlands)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 20, One is already registered
    at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
    at thebetweenlands.common.TheBetweenlands.preInit(TheBetweenlands.java:130)
```
BetweenLands maybe?

**Comment by Sulferix** [comment]
"ill attatch my mod list with this unrelated crash log."

use your eyeballs please

**Comment by OreCruncher** [comment]
*sigh*  With this attitude I will think about helping you.
