### ISSUE TITLE
1.12.2 Crash in the loading screen.

### ISSUE THREAD

**Issue by AwesomeStony** [OreCruncher/DynamicSurroundings#778]
Hello there,
i have a crash at the end of minecraft modded loading screen.

mod version : 1.12.2-3.6.2.1

Forge : 14.23.5.2854

Client log :
https://pastebin.com/eTT9Msuj

Crash log :
https://pastebin.com/DsPTNdhd 

Description : 
I am using a custom version of the rogue like adventure modpack (base modpack : 1.47a) and I added some mods (like 10-15 new mods).

I have installed mixinbootsrap 1.0.5 then I try with mixincompat-0.8 add. I have tried without mixin mod too and with an older version of the mod 3.6.1 ( the old one doesn't even launch the loading screen just insta crash).

DynamicSurroundings is my latest mod added to my list and I get a crash at the end of the launch loading screen.
I use curseforge modpack launcher.

Thanks for your time, and thanks for the effort that you put to make minecraft a better game.
AwesomeStony.

**Comment by OreCruncher** [comment]
Try the latest 3.6.3 BETA version.

**Comment by AwesomeStony** [comment]
Hello, I am back faster than i thought.

I deleted the 2 old mixin plugin.

I tried the latest 3.6.3 Version and get an instant crash ( not even open the loading screen).

No crash report create but here is the client log : 
https://pastebin.com/gxyq7kMc

Hope you can help me, thank you.

**Comment by OreCruncher** [comment]
Try 2855 version of Forge.  You are at 2854.

**Comment by AwesomeStony** [comment]
i updated my forge and still get the instant crash

here my latest client log : 
https://pastebin.com/EJ4n0EW2

**Comment by OreCruncher** [comment]
Can you disable Foamfix to see if you can get past?

**Comment by AwesomeStony** [comment]
i delete foamfix mod and the problem remained

here the log without foamfix : 
https://pastebin.com/Q6DemPv1

**Comment by Greedybaby** [comment]
same with ur problem ,still dont know how to fix 

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from §3动态环绕 (dsurround)
Caused by: java.lang.ExceptionInInitializerError
    at org.orecruncher.dsurround.registry.RegistryManager.initialize(RegistryManager.java:103)
    at org.orecruncher.dsurround.proxy.Proxy.loadCompleted(Proxy.java:92)
    at org.orecruncher.dsurround.ModBase.loadCompleted(ModBase.java:178)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: No enum constant net.minecraft.util.SoundCategory.DS_FOOTSTEPS
    at java.lang.Enum.valueOf(Enum.java:238)
    at net.minecraft.util.SoundCategory.valueOf(SourceFile:8)
    at org.orecruncher.dsurround.registry.sound.SoundRegistry.<clinit>(SoundRegistry.java:67)
    ... 43 more
