### ISSUE TITLE
Error execution script: weather.isNotRaining() && (diurnal.isNight() || diurnal.isSunset()) && !(biome.is('hot') || weather.canWaterFreeze())

### ISSUE THREAD

**Issue by CatbotTsumi** [OreCruncher/DynamicSurroundings#785]
**Mod Version:** 4.0.5.0
**Forge Version:**  36.2.0
**Link to client log:**  [Google Drive Link](https://drive.google.com/file/d/1D9RCfMRbdrEckc0RI4omdPzYtLwul2nY/view?usp=drivesdk
)
**Description:**
These errors are spamming the console. 
Here's a link to my kitchen sink modpack in a zip: [Google Drive Link](https://drive.google.com/file/d/1_o-7rbtYUa4y_2ffJ650lW1Zjpa2yYSS/view)
```
...
[24Nov2021 17:54:45.206] [Render thread/ERROR] [DynamicSurroundings/Lib]: Error execution script: weather.isNotRaining() && (diurnal.isNight() || diurnal.isSunset()) && !(biome.is('hot') || weather.canWaterFreeze())
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: java.lang.NullPointerException: Cannot invoke "javax.script.CompiledScript.eval()" because "func" is null
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.lib.scripting.ExecutionContext.eval(ExecutionContext.java:89)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.scripts.ConditionEvaluator.eval(ConditionEvaluator.java:59)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.scripts.ConditionEvaluator.check(ConditionEvaluator.java:52)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.effects.BlockEffect.canTrigger(BlockEffect.java:82)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.scanner.RandomBlockEffectScanner.blockScan(RandomBlockEffectScanner.java:72)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.scanner.Scanner.tick(Scanner.java:146)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.AreaBlockEffects.process(AreaBlockEffects.java:51)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.Manager.onTick(Manager.java:124)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.Manager.clientTick(Manager.java:141)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.ASMEventHandler_202_Manager_clientTick_ClientTickEvent.invoke(.dynamic)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:105)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1414)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[24Nov2021 17:54:45.207] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.onesix.
OneSixLauncher.launch(OneSixLauncher.java:245)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[24Nov2021 17:54:45.208] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
...
```

**Comment by softestpoly** [comment]
Can confirm that this issue is happening in 1.16.5. Notably, it only happens outside and causes a short, consistent, but very irritating game stutter every time I land.
