### ISSUE TITLE
OreCruncher Spam in Log

### ISSUE THREAD

**Issue by CepheidVariable** [OreCruncher/DynamicSurroundings#788]
**Mod Version**
DynamicSurroundings-1.16.5-4.0.5.0

**Forge Version**
36.2.22

**Link to client log:**
[log.txt](https://github.com/OreCruncher/DynamicSurroundings/files/7738828/log.txt)

**Description:**

Constant spam of [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error in game log.
Several minutes of playing generates log files with over 500,000 entries.
No crashing of the game, but log files are becoming huge, and is causing unnecessary I/O writes.

**Comment by caiovpsilveira** [comment]
Im also getiing oreCruncher spam in log, but caused by a different source. Im getting "[Render thread/ERROR] [DynamicSurroundings/Lib]: Error execution script: weather.isNotRaining() && (diurnal.isNight() || diurnal.isSunset()) && !(biome.is('hot') || weather.canWaterFreeze())"

**Comment by caiovpsilveira** [comment]
Mod version:
DynamicSurroundings-1.16.5-4.0.5.0

Forge version:
36.2.20

Description:
Im also getting kinda the same thing, but im getting two different errors, alternating:

one of them is the same as mentioned above:
[02:06:55] [Render thread/ERROR] [DynamicSurroundings/Lib]: Error compiling script: weather.isNotRaining() && (diurnal.isNight() || diurnal.isSunset()) && !(biome.is('hot') || weather.canWaterFreeze());
[02:06:55] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: java.lang.NoClassDefFoundError: Could not initialize class org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller

the other is the following:
[02:06:49] [Render thread/ERROR] [DynamicSurroundings/Lib]: Error execution script: weather.isNotRaining() && (diurnal.isNight() || diurnal.isSunset()) && !(biome.is('hot') || weather.canWaterFreeze())
[02:06:49] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: java.lang.NullPointerException: Cannot invoke "javax.script.CompiledScript.eval()" because "func" is null

The log can be seen on this link:
https://paste.ee/p/oCPHB

**Comment by rlane85** [comment]
Having the same issue. Playing with slightly modified Crucial 2 modpack running on a VPS docker server. But it only happens on one PC client side...the server and other PCs don't seem to experience it. Forge 36.2.19, same version of DynamicSurroundings

**Comment by Physicist1616** [comment]
DynamicSurroundings 4.0.5.0 is doing this for me, too.  I'm using the same modlist as Etho's Modded Minecraft Season 2 (but most recent versions of them all as of January 5).

MultiMC told me it refused to continue following the logs in real time because it had exceeded 100,000 entries and warned me to fix my mods due to potential disk space issues.  The log files it flushed to disk when I closed the game exceeded 30mb total for an hour or two of playtime, so not dangerously verbose, but it's definitely excessive.  

Standing in a vanilla Plains biome, this is one clump that occurs somewhere around or between 1 and 6 times every two seconds:

> [15Jan2022 14:49:07.062] [Render thread/ERROR] [DynamicSurroundings/Lib]: Error compiling script: weather.isNotRaining() && (diurnal.isNight() || diurnal.isSunset()) && !(biome.is('hot') || weather.canWaterFreeze());
> [15Jan2022 14:49:07.062] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: java.lang.NoClassDefFoundError: Could not initialize class org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller
> [15Jan2022 14:49:07.062] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1509)
> [15Jan2022 14:49:07.062] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:783)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.asCompiledScript(NashornScriptEngine.java:486)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compile(NashornScriptEngine.java:178)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.lib.scripting.ExecutionContext.makeFunction(ExecutionContext.java:103)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.lib.scripting.ExecutionContext.eval(ExecutionContext.java:84)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.scripts.ConditionEvaluator.eval(ConditionEvaluator.java:59)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.scripts.ConditionEvaluator.check(ConditionEvaluator.java:52)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.effects.BlockEffect.canTrigger(BlockEffect.java:82)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.scanner.RandomBlockEffectScanner.blockScan(RandomBlockEffectScanner.java:72)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.scanner.Scanner.tick(Scanner.java:146)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.AreaBlockEffects.process(AreaBlockEffects.java:50)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.Manager.onTick(Manager.java:124)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.Manager.clientTick(Manager.java:141)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.ASMEventHandler_310_Manager_clientTick_ClientTickEvent.invoke(.dynamic)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:105)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1416)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.main.Main.main(Main.java:184)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15Jan2022 14:49:07.063] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> [15Jan2022 14:49:07.064] [Render thread/ERROR] [DynamicSurroundings/Lib]: Error execution script: weather.isNotRaining() && (diurnal.isNight() || diurnal.isSunset()) && !(biome.is('hot') || weather.canWaterFreeze())
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: java.lang.NullPointerException: Cannot invoke "javax.script.CompiledScript.eval()" because "func" is null
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.lib.scripting.ExecutionContext.eval(ExecutionContext.java:89)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.scripts.ConditionEvaluator.eval(ConditionEvaluator.java:59)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.scripts.ConditionEvaluator.check(ConditionEvaluator.java:52)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.effects.BlockEffect.canTrigger(BlockEffect.java:82)
> [15Jan2022 14:49:07.064] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.scanner.RandomBlockEffectScanner.blockScan(RandomBlockEffectScanner.java:72)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.scanner.Scanner.tick(Scanner.java:146)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.AreaBlockEffects.process(AreaBlockEffects.java:50)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.Manager.onTick(Manager.java:124)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.orecruncher.environs.handlers.Manager.clientTick(Manager.java:141)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.ASMEventHandler_310_Manager_clientTick_ClientTickEvent.invoke(.dynamic)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:105)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1416)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraft.client.main.Main.main(Main.java:184)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
> [15Jan2022 14:49:07.065] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [15Jan2022 14:49:07.066] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> [15Jan2022 14:49:07.066] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15Jan2022 14:49:07.066] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> [15Jan2022 14:49:07.066] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
> [15Jan2022 14:49:07.066] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
> [15Jan2022 14:49:07.066] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> [15Jan2022 14:49:07.066] [Render thread/INFO] [STDERR/]: [org.orecruncher.lib.logging.ModLog:error:162]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by ranenvious** [comment]
For what it's worth I'm having a likely related issue, I can't even get to the main menu with dynamic surroundings on. 
it crashes with "java.lang.NoClassDefFoundError: Could not initialize class org.orecruncher.sndctrl.audio.SoundUtils"
https://pastebin.com/5e6LUdKM

I found a similar issue reported https://forums.minecraftforge.net/topic/118293-the-game-crashed-whilst-rendering-overlay-could-not-initialize-class-orgorecrunchersndctrlaudiosoundutils/ however as far as I can tell no other issues have been posted about it specifically in regards to a crash and I'm on the latest version. 

(I am running a quite bloated mod list for reference, but when I remove dynamic surroundings the issue does go away)
https://pastebin.com/gQC385AF
