### ISSUE TITLE
Query - Sound has crashed error

### ISSUE THREAD

**Issue by Nexusdog** [OreCruncher/DynamicSurroundings#87]
*Mod Version:* 1.10.2.3.4.2.0
*Forge Version:* 2297
*Link to crash log (if applicable):* included
*Description:* I experience erratic sound crashes, which may be one of two things - something with DS or a resource pack I'm using. 
This is more of a heads up for you just in case there is a bug, so apologies if this is nothing to do with your mod.

[10:07:35] [Client thread/INFO]: Muting sounds
[10:07:50] [Client thread/INFO]: Unmuting sounds
[10:11:05] [Client thread/INFO]: Default sorting.
[10:11:05] [Client thread/INFO]: Sorting done in 444140ns
[10:12:02] [Server thread/INFO]: [CHAT] You can only sleep at night
[10:12:04] [Server thread/INFO]: [CHAT] You can only sleep at night
[10:13:11] [Server thread/INFO]: nexusdog has just earned the achievement [Uncraft a diamond hoe!]
[10:13:11] [Client thread/INFO]: [CHAT] nexusdog has just earned the achievement [Uncraft a diamond hoe!]
[10:14:27] [Client thread/INFO]: Automatic stack replacement.
[10:22:21] [Client thread/INFO]: Default sorting.
[10:22:21] [Client thread/INFO]: Sorting done in 12394181ns
[10:23:37] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2135ms behind, skipping 42 tick(s)
[10:24:01] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 7106ms behind, skipping 142 tick(s)
[10:24:16] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5114ms behind, skipping 102 tick(s)
[10:24:38] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2053ms behind, skipping 41 tick(s)
[10:25:02] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6243ms behind, skipping 124 tick(s)
[10:25:13] [Thread-26/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[10:25:13] [Thread-26/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.Source.stream(Source.java:953)
[10:25:13] [Thread-26/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at paulscode.sound.StreamThread.run(StreamThread.java:129)
[10:25:18] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4658ms behind, skipping 93 tick(s)
[10:25:21] [Client thread/INFO]: [CHAT] It looks like the sound system has crashed.
[10:25:21] [Client thread/INFO]: [CHAT] Attempting to restart...
[10:25:21] [Client thread/INFO]: [CHAT] 60 fps (2 chunk updates) T: 60
[10:25:21] [Client thread/WARN]: It looks like the sound system has crashed.
[10:25:21] [Client thread/WARN]: Attempting to restart...
[10:25:21] [Client thread/WARN]: 60 fps (2 chunk updates) T: 60
[10:25:21] [Client thread/WARN]: Missing sound for event: dsurround:MISSING
[10:25:21] [Client thread/INFO]: SoundSystem shutting down...
[10:25:26] [Client thread/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[10:25:26] [Client thread/ERROR]: Stream thread did not die!
[10:25:26] [Client thread/INFO]: Ignoring errors... continuing clean-up.
[10:25:27] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[10:25:27] [Sound Library Loader/INFO]: Starting up SoundSystem...
[10:25:27] [Thread-41/INFO]: Initializing LWJGL OpenAL
[10:25:27] [Thread-41/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[10:25:27] [Thread-41/INFO]: OpenAL initialized.
[10:25:27] [Sound Library Loader/INFO]: Sound engine started
[10:25:27] [Thread-41/INFO]: [com.tmtravlr.soundfilters.filters.BaseFilter:checkError:109]: [Sound Filters] Caught AL error in 'loadSourceFilter attempt 1'! Error is 40961
[10:25:27] [Thread-41/INFO]: [com.tmtravlr.soundfilters.filters.BaseFilter:checkError:109]: [Sound Filters] Caught AL error in 'load3SourceFilters attempt 1'! Error is 40963
[10:25:36] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5240ms behind, skipping 104 tick(s)
[10:25:53] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5813ms behind, skipping 116 tick(s)
[10:26:06] [Server thread/INFO]: Saving and pausing game...
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/Overworld
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/Nether
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/The End
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/Deep Dark
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/ExtraUtils2_Quarry_Dim
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/The Dark Realm
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/Omothol
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/The Dreadlands
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/The Abyssal Wasteland
[10:26:06] [Server thread/INFO]: Saving chunks for level '#25_REAL'/Overworld
[10:26:06] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2826ms behind, skipping 56 tick(s)
[10:26:07] [Client thread/INFO]: Muting sounds

**Comment by OreCruncher** [comment]
Yes.  The stream handler in PaulsCode died.  Dynamic Surroundings reinitialized the sound system automatically:
```
10:25:13] [Thread-26/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[10:25:13] [Thread-26/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at paulscode.sound.Source.stream(Source.java:953)
[10:25:13] [Thread-26/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at paulscode.sound.StreamThread.run(StreamThread.java:129)
[10:25:18] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4658ms behind, skipping 93 tick(s)
[10:25:21] [Client thread/INFO]: [CHAT] It looks like the sound system has crashed.
[10:25:21] [Client thread/INFO]: [CHAT] Attempting to restart...
[10:25:21] [Client thread/INFO]: [CHAT] 60 fps (2 chunk updates) T: 60
[10:25:21] [Client thread/WARN]: It looks like the sound system has crashed.
[10:25:21] [Client thread/WARN]: Attempting to restart...
```
If this is causing a problem you can disable in the config options.

**Comment by OreCruncher** [comment]
@Nexusdog Any update on the problem?  Did disabling auto-recovery help?

**Comment by OreCruncher** [comment]
@Nexusdog Going to close out this issue for now.  If you are still having issues let me know and we can continue.
