### ISSUE TITLE
Bird and wind sounds keep on playing in a loop even after returning to main menu

### ISSUE THREAD

**Issue by MatthiasMann** [OreCruncher/DynamicSurroundings#99]
*Mod Version:*
DynamicSurroundings-1.10.2-3.4.5.1.jar
ActualMusic 1.2.0.113.jar

*Forge Version:*
2297 + Optifine D8

*Link to crash log (if applicable):*

*Description:*
Bird and wind sounds keep on playing in a loop even after returning to main menu.

I did not had that issue with version 3.4.5.0 / ActualMusic (installed the update and the music mod at the same time).

I even tried blocking / culling the bird/crow/woodpecker/wind sounds via the in game config - didn't help to get rid of these sounds. (I'm in a plains biome).

I'll try restarting MC with these sounds sets to culled.

**Comment by MatthiasMann** [comment]
Also the sounds do not stop when the game is paused - not sure if this is intended or not.

**Comment by OreCruncher** [comment]
Can you post a client log?  May be something in the log that can reveal what is going on.

**Comment by MatthiasMann** [comment]
The whole log is too big - but I saw lots of these:
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: java.lang.IllegalArgumentException: value already present: PlayerTrackingSound{dsurround:plains, AMBIENT, state=NONE, v=0.040019996, p=1.0, s=1.0, NONE, x=-543.076, y=104.9, z=71.59716}
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:422)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.fokson.actualmusic.proxy.ClientProxy$MusiclessSoundManager.func_148611_c(ClientProxy.java:49)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.client.sound.SoundEngine.playSound(SoundEngine.java:126)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.client.handlers.SoundEffectHandler.playSound(SoundEffectHandler.java:207)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.client.sound.Emitter.update(Emitter.java:114)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.client.handlers.SoundEffectHandler.process(SoundEffectHandler.java:119)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at org.blockartistry.DynSurround.client.handlers.EffectManager.clientTick(EffectManager.java:120)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1014_EffectManager_clientTick_ClientTickEvent.invoke(.dynamic)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:28:35] [Client thread/INFO]: [org.blockartistry.lib.logging.ModLog:error:109]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I also posted these in the comment section of ActualMusic as I didn't saw a github issue tracker linked on the project page.

**Comment by OreCruncher** [comment]
This is what I am looking for.  Now to figure out what is going on.  Thanks!

**Comment by MatthiasMann** [comment]
Seems to be on the ActualMusic side: https://minecraft.curseforge.com/projects/actualmusic?comment=64

**Comment by OreCruncher** [comment]
Yes.  We are in contact trying to get things resolved.

**Comment by OreCruncher** [comment]
@MatthiasMann Between the v3.4.5.2 release of Dynamic Surroundings and ActualMusic v1.2.0.114 the problem should be resolved.  Give a try and let me know how it goes.

**Comment by MatthiasMann** [comment]
Works great - thanks.
